### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by YannickGMZ** [octarine-noise/BetterFoliage#10]
I don't know much about Minecraft Crashs... But I saw your Mod Name in the Null Pointer Exception so I thought there is maybe a bug... Here is the Report: http://pastebin.com/jsJk8EER
EDIT: After starting without LiteLoader the same Problem... EDIT of the EDIT: And starting the game with NO other Mods... Yeah you guessed it... same Problem...

**Comment by YannickGMZ** [comment]
# Forge: 11.14.1.1322:
Optifine
Better Creative Inventory
Better Foliage
Camera Studio
Command Syntax Highlighter
LunatriusCore
InGame Info XML
Schematica
# LiteLoader: 1.8-SNAPSHOT:
Pop Enchant Tags

**Comment by octarine-noise** [comment]
I think I know what the problem is. It's a concurrency issue, because of the multi-threaded rendering in 1.8.

**Comment by YannickGMZ** [comment]
Can you / I fix the Problem in any way?

**Comment by octarine-noise** [comment]
I'll fix it in the next release.

**Comment by YannickGMZ** [comment]
Thank you! :)
