### ISSUE TITLE
Short grass on top of Grass Blocks uses no color if the Grass does not use colorizers.

### ISSUE THREAD

**Issue by kingbdogz** [octarine-noise/BetterFoliage#100]
Hi,

The Grass Blocks in the Aether mod do not colorize their textures, and instead use a strict color scheme. Is there a way that the short grass could take the combined color value of the grass texture if it is not using an in-code colorizer?

Thanks.

**Comment by kingbdogz** [comment]
![image](https://cloud.githubusercontent.com/assets/1280904/20107244/bbc00bc8-a612-11e6-9e86-8b335055cbfc.png)

Here's a screenshot of the problem in action.

**Comment by Zekken01** [comment]
Another example, http://i.imgur.com/NHSwh2P.png

**Comment by octarine-noise** [comment]
Fixed in 2.1.2
