### ISSUE TITLE
Problem with log blocks that have Axis=None

### ISSUE THREAD

**Issue by whichonespink44** [octarine-noise/BetterFoliage#103]
Hello -

One of our users has reported an issue with way Better Foliage is handling log blocks that have been placed by RTG with their AXIS property set to 'none' (6-sided, all-bark model).

See [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3804) and [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2524489-realistic-terrain-generation-rtg-realistic-biomes?comment=3806) for some insight into the nature of the problem.

I was unable to get any additional information with regards to other mods being used (despite asking several times), so I'm just posting this here to make you aware of a potential issue with Axis=None log blocks.

Thanks for your time.

**Comment by octarine-noise** [comment]
Thanks for the heads-up.
I've commented on the RTG thread, and the issue will likely be resolved to everyone's satisfaction.
