### ISSUE TITLE
Agricultural Revolution palm tree logs turn invisible with Better Foliage active

### ISSUE THREAD

**Issue by Shwat** [octarine-noise/BetterFoliage#107]
as the title says Agricultural Revolution palm tree logs turn invisible with Better Foliage active, not sure if this is your mod or their mod, have placed an issue with both.

Cheers.

**Comment by Shwat** [comment]
Sorry, I wrote the wrong mod. Its Agricultural Revolution, not Better Agriculture... my bad..

**Comment by octarine-noise** [comment]
Fixed in 2.1.2

You have to reset your "Block Types" config to default. Additionally, you have to enable the "Round Logs / Default to vertical" option, because AR logs do not have an orientation, and would otherwise get ignored by BF.

**Comment by Shwat** [comment]
Great news! Thanks!
