### ISSUE TITLE
Coral Rendering Black/Dark

### ISSUE THREAD

**Issue by SilverKytten** [octarine-noise/BetterFoliage#109]
BetterFoliage-mc1.7-1.0.14

This happens in SinglePlayer, MultiPlayer, and regardless of any other mods in the environment. 

It's only been happening for a couple of months and I don't have much information on the problem, as it didn't start happening because of any changes, at least that I'm aware of.

![2016-11-28_14 05 23](https://cloud.githubusercontent.com/assets/2188185/20684017/ddd4b8f6-b573-11e6-9447-712b9bbb693e.png)

**Comment by octarine-noise** [comment]
See my answer on #111
