### ISSUE TITLE
1.0.4 for MC1.8 crash when connecting to Spigot server.

### ISSUE THREAD

**Issue by cullorblind** [octarine-noise/BetterFoliage#11]
Testing the 1.8 version, and it works great in SP, but having a few problems with connecting to MP on spigot.  Haven't tried plain vanilla server side yet (maybe tomorrow).  I compiled a fresh copy of spigot and stripped out all mods from the client to make sure there wasn't anything else cluttering up whatever the cause may be.

When I connect to a Spigot 1.8 Server using the Forge 1.8-1322, I'm getting the following:
http://pastebin.com/4h8KHDG7

So I rolled back to Forge 1.8-1319 per a recent post on minecraftforum thread, and it ran okay for about five minutes, but now I'm getting this:
http://pastebin.com/4h8KHDG7

Let me know if you need any more info and I'll try my best to pull it all together.

**Comment by octarine-noise** [comment]
Same bug as #10, fixed in version 1.1.0.

The crash should be gone, but if you experience visual glitches (algae, coral, reeds not showing up properly) feel free to reopen the issue.

**Comment by cullorblind** [comment]
Awesome.. I'll give it a run through it's paces when I get back home..

Thanks for the quick response.
