### ISSUE TITLE
1.7.10 bugs

### ISSUE THREAD

**Issue by SilverKytten** [octarine-noise/BetterFoliage#111]
I'm having some issues with versions 1.7-1.0.13 through 1.0.15:

1) When the config is changed in-game, it doesn't update to the actual text config - But the changes save even after completely closing Minecraft. 
2) When the text config is edited and saved, the changes don't go through to the game.
3) After starting with a fresh install, BF's config no longer generates.
4) Coral renders as black/dark enough that you can't really tell what the colours are. (Reported a few days ago, but mentioning it again here for emphasis)

I've tried using the 1.7-2.0.X versions, however they cause the client to crash upon loading up a world. 

I'm using Forge version 1614

**Comment by octarine-noise** [comment]
BF versions 1.x are no longer supported since 2.0 came out. It's almost been a year, and the issues you see are probably due to Forge changes during that time. I'm actually surprised it works _at all_.

Please submit a report of the crash you're having with 2.0.14 instead (with logs).

**Comment by SilverKytten** [comment]
Will do.
