### ISSUE TITLE
MCVersion Annotation Not found

### ISSUE THREAD

**Issue by PokePugx** [octarine-noise/BetterFoliage#114]
Hello! When I updated Better Foliage (1.7.10-2.0.14) every time I try to load Minecraft it tells me that the mod does not have an MCVersion Annotation available. I have tried installing various versions of the 1.7.10 mod and while the app has always worked for me before, it hasn't been suddenly.

**Comment by octarine-noise** [comment]
Don't worry about it, it's harmless. The 1.10 and 1.11 versions have this already set.
