### ISSUE TITLE
Nothing showing up on 1.11.2

### ISSUE THREAD

**Issue by Multipixelone** [octarine-noise/BetterFoliage#116]
No custom assets show up on 1.11.2, the mod seems to load fine, and the menu shows up and all, but nothing is changed in game

**Comment by octarine-noise** [comment]
Is this still going on? Can you give me some more information?

**Comment by Konlii** [comment]
I think I had the same problem with Better Foliage 2.1.3 in 1.11.2.  Rounded logs were invisible.  No leaf or grass effects.  I have a lot of other mods installed, but didn't take the time to see if one of them was causing a conflict.

Fortunately, it isn't happening in 2.1.4.  Everything seems to work now.
