### ISSUE TITLE
[1.11.2] Forestry rounded-log compatibility broken

### ISSUE THREAD

**Issue by leagris** [octarine-noise/BetterFoliage#117]
When Applied to Forestry Logs, rounded makes log invisible.
![image](https://cloud.githubusercontent.com/assets/1111474/22905686/7d7e4642-f241-11e6-9131-695fd398b7d3.png)

**Comment by mezz** [comment]
As a quick workaround, can the Forestry logs be blacklisted from this transformation?

**Comment by TychoMark** [comment]
mezz
Yeah, I could. Logs visible now. But that's not fix, logs not rounded :)
p.s. I blacklisted this type: forestry.arboriculture.blocks.BlockForestryLog

**Comment by ghost** [comment]
yeah please fix this i really like betterfoliage mod and rounded logs

**Comment by Endmateria** [comment]
Verifying that this is still an issue...  As per these versions, none of the Forestry logs are rendering with the rounded log option applied.  I imagine that this might also affect the Gendustry mod (Forestry add-on), given that that mod is capable of creating "mutated" variants of some Forestry trees, though I haven't tested that yet.   

MC version 1.11.2
Forestry 1.11.2-5.3.3.75
BetterFoliage-MC1.11.2-2.1.3

@mezz @TychoMark Thanks for the temporary workaround!

**Comment by octarine-noise** [comment]
Fixed in 2.1.4
