### ISSUE TITLE
Crash (mod compatibility)

### ISSUE THREAD

**Issue by ghost** [octarine-noise/BetterFoliage#119]
it is very steady to be crashed.
[crash-2017-03-01_18.23.36-client.txt](https://github.com/octarine-noise/BetterFoliage/files/811162/crash-2017-03-01_18.23.36-client.txt)
[crash-2017-03-01_18.16.52-client.txt](https://github.com/octarine-noise/BetterFoliage/files/811163/crash-2017-03-01_18.16.52-client.txt)
[crash-2017-03-01_18.14.26-client.txt](https://github.com/octarine-noise/BetterFoliage/files/811164/crash-2017-03-01_18.14.26-client.txt)
https://github.com/sp614x/optifine/issues/513

**Comment by octarine-noise** [comment]
The error message says you ran out of memory. Either you have a too low setting in your launcher's config, or you set the view distance ridiculously high. I can't think of anything else.

Either way, I can't do anything about it.
