### ISSUE TITLE
Weird Render Error

### ISSUE THREAD

**Issue by YannickGMZ** [octarine-noise/BetterFoliage#12]
The Grass and the Leaves Render in a weird way..
Pic1: http://goo.gl/jCfw3s
Pic2: http://goo.gl/lEY2Um
Mods:
BetterFoliage-mc18.1.1.0.jar
Optifine_1.8.0_HD_U_D1.jar
Optifine Settings: http://goo.gl/FVd3Xv

**Comment by octarine-noise** [comment]
Anisotropic Filtering is not supported ATM.

Better Foliage is not the only mod having this issue with Optifine, so I'm holding back on this for now.
