### ISSUE TITLE
The connected grass model is cataclysmically bad

### ISSUE THREAD

**Issue by purpleposeidon** [octarine-noise/BetterFoliage#120]
No culling of a block that shows up absolutely everywhere.

What it should look like (and does w/ connected grass disabled): ![](http://i.imgur.com/LePXtgG.jpg)

What it actually looks like: ![](http://i.imgur.com/Qap5f2P.png)

This makes the typical world's surface about 5 times more expensive to render than it ought to be.

**Comment by octarine-noise** [comment]
Well, this is embarrassing. And this has been going on ever since 2.0. Thanks for noticing. I never knew that spectator mode has noclip, but I'll use it from now on.

Fixed in 2.1.4
