### ISSUE TITLE
Wrong grass shade

### ISSUE THREAD

**Issue by e3valdas** [octarine-noise/BetterFoliage#121]
The _upper_ grass is dark green, and your mod's tweaked _lower_ grass is always bright. Its color isn't affected by biome like it should.

_I am using xisumavoid's Vanilla Tweaks resource pack - grassy sides._

![2017-04-02_15 47 10](https://cloud.githubusercontent.com/assets/16884509/24619187/e0172b1c-18a1-11e7-8d1d-4d7b64cc24f6.png)
![2017-04-02_15 47 21](https://cloud.githubusercontent.com/assets/16884509/24619192/e34ae562-18a1-11e7-8a15-072cbee6e80e.png)

**Comment by VOiDProXy** [comment]
I had a similar issue the other day, I have Optifine + Better Foliage and they were both trying to transform the grass side textures. 
I ended up turning off the grass feature in Better Foliage and let OptiFine do the job. You can do this via the main menu > mod options > better foliage > connected grass textures. You can choose to turn off OptiFine's Fancy Grass too, It's up to you which one you prefer.

**Comment by e3valdas** [comment]
Well yes... But you see... OptiFine renders grass only on 1 layer of the block, but Better Foliage renders it on an extra layer beneath it, so it's 2 in total.

**Comment by VOiDProXy** [comment]
I'm sorry if I'm misunderstanding you, if you turn off one of either of them, there should only be one layer rendering (either OptiFine's or BetterFoligage) - Since there'd only be one layer, it should fix up the shading on the grass. At least, that's how I see it. But perhaps I am misunderstanding you, in which case I'm sorry :)

**Comment by e3valdas** [comment]
I found out something interesting yesterday. The color is affected by shaders. If you have shaders (I'm using Sildur's Medium), the color will be wrong, but if you don't have shaders, everything will look fine.

**Comment by octarine-noise** [comment]
Optifine and BF connected grass are not meant to be used together. Just pick the one you like more.

If you still have coloring issues with BF connected grass alone, I'll reopen the issue.

**Comment by inboundbark** [comment]
This is a shader issue, not an optifine better grass issue. If you use a different shaderpack like seus renewed the issue goes away.
