### ISSUE TITLE
Foamfix conflict

### ISSUE THREAD

**Issue by Endmateria** [octarine-noise/BetterFoliage#122]
Just wanted to let you know that Foamfix's new update "FoamFix 0.6.2 beta 3 Anarchy" is causing all the rounded tree logs to turn invisible, both with modded trees from BOP/Forestry, and vanilla tree (MC version 1.11.2).  Don't know if it is a screw-up on their end or what, but I know this is a recent problem as I've been using both your mod and Foamfix together for a while now.  Not a big deal, I know the anarchy version of that mod messes with a lot of sensitive code, just thought I'd bring it to your attention for the sake of saving you from future troubleshooting.  Thanks for this mod by the way, it's definitely a "must have".

**Comment by octarine-noise** [comment]
Better Foliage is currently not compatible with the parallel model baking feature from FoamFix. See [FoamFix/44](https://github.com/asiekierka/FoamFix/issues/44).
