### ISSUE TITLE
Better Foliage breaks shaders adding the "Waving Grass" effect

### ISSUE THREAD

**Issue by MadByteDE** [octarine-noise/BetterFoliage#125]
For some reason after installing Better Foliage the "Waving Grass" effect of the shader breaks and tall grass and sugar cane look like this:
![2017-04-17_20 04 33](https://cloud.githubusercontent.com/assets/4752038/25098606/80766a7a-23a9-11e7-95c8-989a242c175f.png)

Normally sugar cane shouldn't wave at all and without Better Foliage installed it doesn't. 
Deactivating any options in Better Foliage doesn't help.

Minecraft Version: 1.10.2
Mod Version: 2.1.4

**Comment by octarine-noise** [comment]
Blocks that are on the crops whitelist (under block types) will wave in the wind. I've just moved reeds and double plants over to the blacklist in 2.1.4, but I guess you've upgraded from an earlier version. Setting the crops whitelist/blacklist back to default should get rid of the effect.
