### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SwordShaman** [octarine-noise/BetterFoliage#126]
---- Minecraft Crash Report ----

WARNING: coremods are present:
SHLoadingPlugin (ScalingHealth-1.11.x-1.0.5-47.jar)
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
FarseekCoreMod (Farseek-1.11-2.1.jar)
IvToolkit (IvToolkit-1.3.2.1.jar)
LoadingPlugin (Quark-r1.2-90.jar)
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.6.0.jar)
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
PotionCoreFMLLoadingPlugin (PotionCore-1.5_for_1.11.2.jar)
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 4/19/17 11:33 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
at net.minecraft.client.renderer.block.model.FaceBakery.func_178404_a(FaceBakery.java:202)
at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:189)
at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:112)
at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:76)
at net.minecraft.client.renderer.block.model.FaceBakery.func_178414_a(FaceBakery.java:58)
at BlockModelUtils.makeBakedQuad(BlockModelUtils.java:84)
at BlockModelUtils.makeModelCube(BlockModelUtils.java:61)
at BetterGrass.update(BetterGrass.java:73)
at TextureUtils.resourcesReloaded(TextureUtils.java:295)
at TextureUtils$1.func_110549_a(TextureUtils.java:338)
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
at TextureUtils.registerResourceListener(TextureUtils.java:342)
at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2751)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1282)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.11.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 226316544 bytes (215 MB) / 523501568 bytes (499 MB) up to 8576565248 bytes (8179 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.38 Powered by Forge 13.20.0.2282 Optifine OptiFine_1.11.2_HD_U_B7 51 mods loaded, 58 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
U	minecraft{1.11.2} [Minecraft] (minecraft.jar)
U	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2282.jar)
U	forge{13.20.0.2282} [Minecraft Forge] (forge-1.11.2-13.20.0.2282.jar)
U	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar)
U	potioncore_coremod{1.5_for_1.11.2} [Potion Core Coremod] (minecraft.jar)
U	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.9.jar)
U	animania{1.0.4.6} [Animania] (animania-1.11.2-1.0.4.6.jar)
U	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar)
U	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.0.1.jar)
U	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar)
U	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar)
U	betterwithmods{1.1.6} [Better With Mods] (Better With Mods-1.1.6-1.11.2.jar)
U	betterfoliage{2.1.4} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.4.jar)
U	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.11-1.5.1.jar)
U	botania{r1.9-342} [Botania] (Botania r1.9-342.jar)
U	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.2-1.11.2.jar)
U	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar)
U	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.24.jar)
U	crafttweaker{3.0.24} [Crafttweaker] (CraftTweaker-1.11.2-3.0.24.jar)
U	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.24.jar)
U	dsurround{3.3.6.0} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.3.6.0.jar)
U	enhancedvisuals{1.0} [Enhanced Visuals] (EnhancedVisuals v1.0.12 mc1.11.2.jar)
U	fbp{2.2} [Fancy Block Particles] (FancyBlockParticles-1.11.2-2.2.jar)
U	farseek{2.1} [Farseek] (Farseek-1.11-2.1.jar)
U	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar)
U	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar)
U	itemzoom{1.5} [Item Zoom] (itemzoom1.11.2-1.5.jar)
U	jei{4.3.3.266} [Just Enough Items] (jei_1.11.2-4.3.3.266.jar)
U	levelup{${version}} [Level Up!] (LevelUp!-0.14.4-1.11.2.jar)
U	minecolonies{1.11-0.6.3360} [MineColonies] (minecolonies-universal-1.11-0.6.3360.jar)
U	placeableitems{3.0.4} [Placeable Items Mod] (placeableitems-3.0.4.jar)
U	potioncore{1.5_for_1.11.2} [Potion Core] (PotionCore-1.5_for_1.11.2.jar)
U	primal{0.3.14} [PrimalCore] (PrimalCore-0.3.14.jar)
U	qualitytools{1.0.1_for_1.11.2} [Quality Tools] (QualityTools-1.0.1_for_1.11.2.jar)
U	quark{r1.2-90} [Quark] (Quark-r1.2-90.jar)
U	rfpr{8.1.1} [Real First-Person Render] (Real First-Person Render-1.11.2-8.1.1.jar)
U	realdrops{1.1.10} [Realistic Item Drops] (RealisticItemDrops-1.1.10.jar)
U	reccomplex{1.2.10} [Recurrent Complex] (RecurrentComplex-1.2.10.jar)
U	roots{0.015} [Roots 2] (roots-2-0.015.jar)
U	scalinghealth{1.0.5} [Scaling Health] (ScalingHealth-1.11.x-1.0.5-47.jar)
U	silentlib{2.1.0} [Silent Lib] (SilentLib-1.11.x-2.1.0-53.jar)
U	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar)
U	spiceoflife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.11.2-1.3.8.jar)
U	streams{0.3} [Streams] (Streams-1.11-0.3.jar)
U	survivalist{1.9.0} [Survivalist] (Survivalist-1.11.2-1.9.0.jar)
U	tp{2.2.0-Hotfix} [Tiny Progressions] (tinyprogressions-1.11.2-2.2.0-Hotfix.jar)
U	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar)
U	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.11.2-1.1.2.jar)
U	waddles{0.5.1} [Waddles] (Waddles-1.11-0.5.1.jar)
U	waystones{3.0.13} [Waystones] (Waystones_1.11.2-3.0.13.jar)
Loaded coremods (and transformers):
SHLoadingPlugin (ScalingHealth-1.11.x-1.0.5-47.jar)
net.silentchaos512.scalinghealth.asm.SHClassTransformer
AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
squeek.applecore.asm.TransformerModuleHandler
FarseekCoreMod (Farseek-1.11-2.1.jar)
farseek.core.FarseekClassTransformer
IvToolkit (IvToolkit-1.3.2.1.jar)

LoadingPlugin (Quark-r1.2-90.jar)
vazkii.quark.base.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.3.6.0.jar)
org.blockartistry.mod.DynSurround.asm.Transformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.4.jar)
mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (Bloodmoon-MC1.11-1.5.1.jar)
lumien.bloodmoon.asm.ClassTransformer
PotionCoreFMLLoadingPlugin (PotionCore-1.5_for_1.11.2.jar)
com.tmtravlr.potioncore.asm.ArmorHandlerTransformer
TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
toughasnails.asm.transformer.BlockCropsTransformer
toughasnails.asm.transformer.EntityRendererTransformer
toughasnails.asm.transformer.WorldTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
brad16840.common.asm.ClassTransformer
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.65' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
Launched Version: 1.11.2-forge1.11.2-13.20.0.2282
LWJGL: 2.9.4
OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.65, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: Realistico.zip (incompatible), Realistico Addon.zip (incompatible)
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by octarine-noise** [comment]
Can you try the same modlist without Better Foliage? I don't think it's my fault.
