### ISSUE TITLE
Client Crash - java.lang.ClassCastException: mods.betterfoliage.common.util.OffsetBlockAccess cannot be cast to net.minecraft.world.ChunkCache

### ISSUE THREAD

**Issue by SirWilli** [octarine-noise/BetterFoliage#13]
Fastcraft is enabled, not sure if this is the issue.
Crash report: http://pastebin.com/C6jY63KX

**Comment by octarine-noise** [comment]
Fastcraft is fine, but BF is not compatible with Colored Lights.

I'm not sure yet what can be done.

**Comment by SirWilli** [comment]
Okay, maybe @CptSpaceToaster has an idea.

**Comment by CptSpaceToaster** [comment]
wah?

**Comment by SirWilli** [comment]
Oh, I think I mixed up the colored lights in the mod PixelUtilities with the mod called "Colored Light", sorry. :3

**Comment by CptSpaceToaster** [comment]
no no... this is me

**Comment by SirWilli** [comment]
Okay, so BetterFoliage does have issues with colored lights and does crash the client if world get loaded but @octarine-noise is not sure how he can fix the issue I think.

**Comment by CptSpaceToaster** [comment]
Well... I can look later... :)

**Comment by octarine-noise** [comment]
Not sure *yet*. I'm looking into it. I was always unhappy with that trick using the **OffsetBlockAccess** anyway, and it seems to violate an assumption made by CLC code. I'll try to find a better way and sidestep this issue.

This is definitely a new thing, as I can recall BF and CLC working together just fine before.

**Comment by CptSpaceToaster** [comment]
Let me know if you need me to turn a wrench.

**Comment by SirWilli** [comment]
So PixelUtilties needs to update CLC?
Can I just replace the "coloredlightscore" folder in PixelUtilties with the latest?

**Comment by CptSpaceToaster** [comment]
> so I tested. Latest versions of BF, CLC and FastCraft: Stuff Works Fine(tm). Closing.

**Comment by SirWilli** [comment]
Just tried to replace it, unfortunately it doesn't work.

**Comment by octarine-noise** [comment]
What versions do you use? I mean Forge, BF, CLC and FastCraft.

**Comment by CptSpaceToaster** [comment]
alternatively... crash reports....

**Comment by SirWilli** [comment]
BetterFoliage: 1.7-1.0.4 Forge: 1.7.10-10.13.2.1277, fastcraft: 1.19, PixelUtilties: 3.3.7 (Not sure which version of CLC is in it.)

Crash report of what? In my first post is a crash report.

**Comment by CptSpaceToaster** [comment]
make sure you have the latest CLC version: You can download it here: http://coloredlightscore.us.to:8080/job/ColoredLightsCore%20v1.7.10/

The file is named ColoredLightsCore-1.3.7.37.jar
The version is 1.3.7.37.  Please load use THAT, along with the latest available versions of Forge, FastCraft, and PixelUtilities.

If you experience a crash after updating everything, please paste the NEW crash report.  Even if it looks the same to you, we need the updated information it has.  Please don't exclude a crash report if you changed something.  If you changed something, and still got the crash, then we'd like to have BOTH reports.

**Comment by octarine-noise** [comment]
True... sorry, force of habit.

Your CLC is 1.1.2, which is very old. I suggest updating it.
Also, PixelUtilities is carrying CLC? Are they allowed to do that?

**Comment by CptSpaceToaster** [comment]
You know... I think ClientHax just Fat-jarred it in... because he was being naughty...

Which is probably the source of the confusion.  I release under the WTFPL, so it's not against any agreement or anything, but this is a little ridiculous...

**Comment by clienthax** [comment]
As CLC was unstable at the time, our build contained fixes for cauldron servers which have since been moved into master, clc is not present in the latest builds of pixelutils.
https://mega.co.nz/#!WQN1DCAZ!9lfdODZFe4g98uldVXnG3a0oSSxP2TDNFQgqswnIe9U

**Comment by CptSpaceToaster** [comment]
Welcome to BetterFoliage!

**Comment by SirWilli** [comment]
I already have the latest PixelUtilties version (3.3.7). Seems that I can't use betterfoliage then.

**Comment by clienthax** [comment]
sirwilli, did you use the link i put up?

**Comment by SirWilli** [comment]
No because I can't join with version 3.3.5 on a server with 3.3.7

**Comment by clienthax** [comment]
so i can only assume that you are a idiot who doesn't understand the purpose of TESTING

**Comment by octarine-noise** [comment]
No name-calling please. Work it out like civilized people.

**Comment by clienthax** [comment]
@octarine-noise when i take time out of my day to try and resolve something because multiple people failed to read or google a issue, it annoys me when they don't bother to try what i say.

**Comment by SirWilli** [comment]
You didn't asked for testing it. The version you posted works with BetterFoliage.
