### ISSUE TITLE
Seeing though leaves

### ISSUE THREAD

**Issue by Kehaan** [octarine-noise/BetterFoliage#130]
![2017-05-15_18 59 57](https://cloud.githubusercontent.com/assets/6755642/26070030/58cbe346-39a3-11e7-8d43-9d52499ac19d.png)
Using newest Betterfoliage in MC 1.10.2 in my pack Farming Valley on Curse. Makes the issue as shown in above screenshot. Can only be seen on fast gfx.
Removing BetterFoliage fixes the issue.

If you need any logs let me know :)

**Comment by Darkosto** [comment]
Can confirm, this is happening to me on 1.11.2, too. Also confirming only happening on "fast" graphics settings.

MC: 1.11.2
Forge: 2304
Better Foliage: 2.1.5

Thank you!

**Comment by octarine-noise** [comment]
Fixed in 2.1.7
