### ISSUE TITLE
Textures not working properly.

### ISSUE THREAD

**Issue by sinkingsage** [octarine-noise/BetterFoliage#133]
I installed it in my 1.11.2, it worked correctly, after a while it started to look like this:
![2017-05-30_19 55 32](https://cloud.githubusercontent.com/assets/8989318/26599819/dd589a8a-4571-11e7-9399-282be9a09a72.png)
Most textures are flat or outright transparent, I've reinstalled, reset the settings, deleted the forge mod file, nothing fixed it, what could be causing this?

**Comment by octarine-noise** [comment]
From the looks of it, you have Optifine installed, and Anisotropic Filtering enabled. AF is not compatible with Better Foliage, you'll have to switch it off.
It's a long-standing bug I haven't had the time and motivation to track down yet.

**Comment by sinkingsage** [comment]
That's exactly what it was, too bad, I think both at the same time would look amazing.

**Comment by zauberparacelsus** [comment]
It isn't just Anisotropic Filtering.  I also had to turn off Antialiasing.

**Comment by octarine-noise** [comment]
Fixed in 2.1.7
