### ISSUE TITLE
Invisible blocks - MC 1.12 - BetterFoliage-MC1.12-2.1.6.jar

### ISSUE THREAD

**Issue by DaimeneX** [octarine-noise/BetterFoliage#140]
When playing on MC 1.12 with Optifine I have issues with "Connected Grass Textures" and "Round Logs" which cause these invisible textures to pop everywhere.
Extremely noticeable on mountains.
![2017-07-07_17 52 42](https://user-images.githubusercontent.com/27635283/27965862-6bd02d58-633d-11e7-9c7e-0ba3eec8b33d.png)
![2017-07-07_17 52 46](https://user-images.githubusercontent.com/27635283/27965864-6bd7c7a2-633d-11e7-8451-524ff3ce7c27.png)
![2017-07-07_17 53 07](https://user-images.githubusercontent.com/27635283/27965863-6bd6021e-633d-11e7-8397-d44cc26a4dce.png)
![2017-07-07_17 51 36](https://user-images.githubusercontent.com/27635283/27965865-6bd9018a-633d-11e7-91c1-e99b72019f1f.png)
![2017-07-07_17 52 27](https://user-images.githubusercontent.com/27635283/27965866-6bdac70e-633d-11e7-8c32-bfa4a091a636.png)

**Comment by nephatrine** [comment]
I have same issue on 1.11.2 using Better Foliage 2.1.6. I did not experience this with the previous version.

**Comment by dungzaz** [comment]
Me too. T-T

**Comment by kazuma777** [comment]
Go to options -> video settings-> quality and change mipmap levels:1 to levels:4.
It's working for me :)

**Comment by octarine-noise** [comment]
Derp :)

Fixed in 2.1.7
