### ISSUE TITLE
Effect doesnt work

### ISSUE THREAD

**Issue by McAsulys** [octarine-noise/BetterFoliage#146]
I installed the mod on 1.12.1 forge, the mod was loaded correctly, i can access to the option menue, but nothin is apend in my game, the effect is'nt present. I don't know why. I was using this mod on the 1.11.2 and all work correcly. May be it need being compiled with 1.12.1 forge. I don't know.

**Comment by TheStilbruch** [comment]
I am having the same issue.

**Comment by NJDaeger** [comment]
Yeah, same.

**Comment by MadByteDE** [comment]
Yep same.

**Comment by Leeo97one** [comment]
Same for me too.

**Comment by octarine-noise** [comment]
I've already uploaded BF 2.1.9 which works under MC 1.12.1, but Curse is taking a long time to approve the file. Try it out when it becomes available.

**Comment by Leeo97one** [comment]
It works now, thanks!
