### ISSUE TITLE
Better With Mods HCStumping log problems

### ISSUE THREAD

**Issue by PaperTriangle** [octarine-noise/BetterFoliage#152]
The stump blocks from Better With Mods don't render as round logs even when added to the whitelist as "betterwithmods.common.blocks.BlockStump" unless "Default to vertical" is true.

Is there a custom "Wood Log Model" that I could add to get this working without every log being vertical?

**Comment by octarine-noise** [comment]
You can set the option to true without worries. Not all logs will be vertical, only the ones that don't have an axis defined - like BWM stumps.

Logs that do have an axis (i.e. you can place them sideways, not just vertical) will still have their proper orientation.
