### ISSUE TITLE
WTF Expedition tree roots

### ISSUE THREAD

**Issue by Vampsku11** [octarine-noise/BetterFoliage#155]
While not an issue with BetterFoliage itself, I would like to be able to chamfer the roots on the trees from WTF's Expedition mod. These blocks are placed around the base of his trees and are logs with bark on six sides. Is there an explanation on how I can edit betterfoliage.cfg to modify those blocks?

**Comment by octarine-noise** [comment]
You have to enable the config option Round Logs / Default to vertical

Since they don't have an orientation defined on the block, they'll always be pointing upward. There's no way around this.

**Comment by Vampsku11** [comment]
Thank you, I set that and while it's not a perfect solution it does blend the "roots" better with the rest of the logs in the world. I'm not seeing that option enabled having any adverse effects otherwise.
![2017-09-30_20 13 03](https://user-images.githubusercontent.com/20630582/31051065-cb5cfcc6-a61b-11e7-9bc5-1a9119ffeb10.png)
