### ISSUE TITLE
Natura Missing Compatibility

### ISSUE THREAD

**Issue by theDaleighChronicle** [octarine-noise/BetterFoliage#164]
![2018-01-08_14 56 19](https://user-images.githubusercontent.com/26281804/34694408-43a47d06-f484-11e7-9410-6613a6fcb4c3.png)
![2018-01-08_14 57 11](https://user-images.githubusercontent.com/26281804/34694409-43c5c34e-f484-11e7-9b71-da5517254bd4.png)

The leaves are missing compatibility since the newest update.

**Comment by ghost** [comment]
agreed...https://github.com/OreCruncher/DynamicSurroundings/issues/199

**Comment by ghost** [comment]
you can close this issue. cus it's fixed at natura's side.
https://github.com/progwml6/Natura/issues/424#issuecomment-356462605
