### ISSUE TITLE
No change on some grass blocks

### ISSUE THREAD

**Issue by Zeexx** [octarine-noise/BetterFoliage#168]
Hi guys,

Like you can see on the screenshot, there are some grass blocks who dont change with BetterFoliage.
I think its not normal so i post here for some solution.

https://image.noelshack.com/minis/2018/04/4/1516860566-grass.png

Hope my english is not too awful.
Sincerely, zayx!

PS: on Minecraft 1.12.2

**Comment by Revvilo** [comment]
I was just passing through, but it looks like grass without a block beneath it makes it do that.
Your english was fine, but that image was absolutely tiny! :)

<img src="https://user-images.githubusercontent.com/13816212/39668210-63be5960-511b-11e8-8a64-042bee7e4022.png" width="200"/> <img src="https://user-images.githubusercontent.com/13816212/39668212-69e32dac-511b-11e8-8d7c-8d72587d25d6.png" width="200"/>

**Comment by danibot-dz** [comment]
Correct! absolutely correct, Revvilo. Zeexx you should close your issue report, as this is not a issue.
