### ISSUE TITLE
Crash with Localized Weather & Stormfronts Mod v2.3.7

### ISSUE THREAD

**Issue by louisw22** [octarine-noise/BetterFoliage#18]
http://openeye.openmods.info/crashes/01175c074c5b478be57dac3681ad6dd7

Crashes on world load or after new world creation

**Comment by octarine-noise** [comment]
I could not see any issues in conjunction with Weather mod, this bug is pure BetterFoliage.

It's fixed in 1.0.11.

**Comment by louisw22** [comment]
OK thanks

On 29 Apr 2015 10:49, octarine-noise <notifications@github.com> wrote:I could not see any issues in conjunction with Weather mod, this bug is pure BetterFoliage.

It's fixed in 1.0.11.
