### ISSUE TITLE
Crash with 1.0.9 and 1.0.10 of Better Foliage

### ISSUE THREAD

**Issue by Haggle1996** [octarine-noise/BetterFoliage#19]
https://gist.github.com/Haggle1996/309f3a3665fac89d37eb

Happens on either 1.7.10 versions 1.0.9 or 1.0.10. I'm sure its a mod incompatibility, just trying to figure it out.

**Comment by DevonX** [comment]
I have the same issue

**Comment by octarine-noise** [comment]
Fixed (hopefully) in 1.0.11

**Comment by octarine-noise** [comment]
Fixed for real in 1.0.12
