### ISSUE TITLE
1.12.2 Client Crash with newest Forge

### ISSUE THREAD

**Issue by Endmateria** [octarine-noise/BetterFoliage#206]
Forge Version 1.12.2 - 14.23.4.2765
Better Foliage Version 1.12-2.1.10

Game crashes @ launch
http://www.minecraftforge.net/forum/topic/66642-1122-game-crashforge-2765-stack-overflow/

**Comment by KenyMylankca** [comment]
yeah your mod crashes with Forge 2763+ (2763 included)

**Comment by pixzi** [comment]
Same issue here, tried without BF and it works perfectly fine.

**Comment by Grrpapa** [comment]
I have same issue which started with Forge 2763 and continues throughout 2764 and 2765.

**Comment by KenyMylankca** [comment]
no doubt it's a bug, and the author should fix it. posting agreement comments won't help. we should wait

**Comment by Endmateria** [comment]
I agree with @KenyMylankca

**Comment by octarine-noise** [comment]
Fixed in 2.2.0
