### ISSUE TITLE
I dunno whats wrong but it looks like something about quark and better folliage in the new version of forge

### ISSUE THREAD

**Issue by DATA-xPUNGED** [octarine-noise/BetterFoliage#211]
here the error: https://notepad.pw/ERROR

**Comment by Excaliburning** [comment]
Read the other post before creating another issue.
This is identical to #209 and is not because of Quark.
Better Foliage has an issue with the recent versions of Forge.

**Comment by Psy-Virus** [comment]
Yeah, Quark did nothing wrong. But I guess for some latinum you can spend some time in a holosuite and forget the trouble.

**Comment by octarine-noise** [comment]
Does that log even come from Minecraft? Looks like a copy-paste misfire to me.

Anyway, your problem should be fixed in 2.2.0
