### ISSUE TITLE
Better Foliage 1.0.12 Random Crash

### ISSUE THREAD

**Issue by Haggle1996** [octarine-noise/BetterFoliage#23]
Sporadically receiving this error with Better Foliage:

https://gist.github.com/Haggle1996/c2ec38d13378421177d5

It has only occurred so far on world load or dimension transition to the overworld. Never during regular play. Reloading the world (sometimes two or three times) will eventually make the error go away.

Edit: I do have FastCraft 1.21 installed.

**Comment by octarine-noise** [comment]
Should be fixed in 1.0.13.
