### ISSUE TITLE
A way to disable the rounding of Twilight Forest Oak Logs?

### ISSUE THREAD

**Issue by katubug** [octarine-noise/BetterFoliage#241]
Hi there! Firstly, thank you for the great mod! I'm having an issue though, where the rounded logs look really strange on the big Twilight Oak trees. Here's a screenshot where you can see right through it:

![2019-05-25_20 31 29](https://user-images.githubusercontent.com/20935286/58376255-20f92c00-7f2c-11e9-9ec7-6d05ff84de53.png)

I don't want to disable all rounded logs, but I would like to blacklist that particular type, if possible.

I tried adding "tile.twilightforest.Log.0" (which I got from inside the mod's .jar file, in the en_us.lang) to the "S:logClassesBlacklist," but when I reloaded my game, the logs I'd placed were still rounded.

When that didn't work, I also tried: "tile.twilightforest.Log" (same but without the 0) and "twilightforest:twilight_log" (the name according to /print_item), but still no luck.

What am I doing wrong? Thanks in advance for your help!

**Comment by ChloeDawn** [comment]
The config uses classes, not id's. you need [`twilightforest.block.BlockTFLog`](https://github.com/TeamTwilight/twilightforest/blob/1.12.x/src/main/java/twilightforest/block/BlockTFLog.java)

**Comment by katubug** [comment]
Ah, my mistake! Thank you very much for the help.
