### ISSUE TITLE
Batch of rounded logs won't render correctly

### ISSUE THREAD

**Issue by BoFone** [octarine-noise/BetterFoliage#25]
When I use the same log type to form a big tree with rounded log turned on, the big tree won't show up. The following links are images that demonstrate this issue. One is with rounded log turned on, the other is turned off. 

http://imgur.com/1gw8zbo
http://imgur.com/0N6VX0f

**Comment by Bo-Fone** [comment]
Is this fixed ?

**Comment by octarine-noise** [comment]
I believe so, but rendering has changed completely in 2.0 anyway. Try with the new version, and I'll reopen if it's still a problem.

**Comment by Bo-Fone** [comment]
gotcha, i'll have a test.

**Comment by Bo-Fone** [comment]
thanks!

**Comment by Bo-Fone** [comment]
Also, do you have a update log for the newest version?
