### ISSUE TITLE
Please support 1.14.4 (Forge)

### ISSUE THREAD

**Issue by sepsol** [octarine-noise/BetterFoliage#254]
Any plans?

**Comment by FireSeth** [comment]
I second this.

**Comment by danfiscus** [comment]
Not likely, the developer hasn't been active on GitHub in over a year and this repo is all but archived at this point. We can dream though!

**Comment by FireSeth** [comment]
Any alternatives?

**Comment by sepsol** [comment]
I am currently forced to use [LB Photo Realism](https://www.curseforge.com/minecraft/texture-packs/lb-photo-realism-reload) texture pack. It has some OpenGL issues with OptiFine (I guess) but it's fine. It makes the leaves on the trees to look better, but sadly doesn't have all the good features of [Better Foliage](https://www.curseforge.com/minecraft/mc-mods/better-foliage) mod. Don't get me wrong, that texturepack is dope!

**Comment by octarine-noise** [comment]
Better Foliage 1.5.0 for Forge 1.14.4 is out!
