### ISSUE TITLE
2.3.0 Custom Color crash / Shaders still not working...

### ISSUE THREAD

**Issue by Dean-0822** [octarine-noise/BetterFoliage#263]
https://pastebin.com/Uk6FmHQr
^ Crash report

**Comment by Dean-0822** [comment]
The only way I can get it to work is if I disable custom colors in optifine. I've tried both 1.12.2 HD U F5 as well as HD U F4, and HD U F3. Also, shader integration also seems to break all shader waving effects across the board. I'm gonna have to uninstall this until things are more stable :(

**Comment by octarine-noise** [comment]
Fixed with 2.3.1

Note that you will probably have to change the BF configuration to get waving vegetation to work. Check the [release comment](https://www.curseforge.com/minecraft/mc-mods/better-foliage?comment=711) on Curseforge for the details.
