### ISSUE TITLE
Crash with Mekanism

### ISSUE THREAD

**Issue by mxnmnm** [octarine-noise/BetterFoliage#264]
I tried to place a solar panel to the side of a block right under the world border and because the solar panel has multiple blocks it wouldn't normally let me place but this time I crashed.  It might have to do with the recent update.  If you need more info let me know.

https://paste.dimdev.org/jicemaziva.mccrash

**Comment by mxnmnm** [comment]
I couldn't log into the world until I disabled better foliage

**Comment by octarine-noise** [comment]
Fixed with BF 2.3.1
