### ISSUE TITLE
Crash with latest version of Optifine and BetterFoliage

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [octarine-noise/BetterFoliage#265]
Hello, here are my pertinent versions:

Optifine                    HD_U_F5
BetterFoliage            2.3.0
Forge                        14.23.5.2836

Game crashes on world load with the latest version of both mods

**Comment by JohnnyWoong** [comment]
me too

**Comment by octarine-noise** [comment]
Fixed with BF 2.3.1
