### ISSUE TITLE
[1.10.2] optifine H5 breaks shader support and custom colours 'grid' format (again)

### ISSUE THREAD

**Issue by xemnes** [octarine-noise/BetterFoliage#266]
pretty much the title, where it previously worked on optifine E7, i updated to H5 to find that the leaves are completely the wrong colour due to no longer using the biome colormap 'grid' format
(the extra grass and leaves also no longer work with shaders SSS and waving when it did previously on E7)
![image](https://user-images.githubusercontent.com/603338/71638142-c48f8500-2c4f-11ea-8b70-43be766e3f24.png)

**Comment by octarine-noise** [comment]
Fixed in 2.2.2
