### ISSUE TITLE
Cant figure out blacklist/blacklist not working(probably the former)

### ISSUE THREAD

**Issue by Adraxas** [octarine-noise/BetterFoliage#27]
Trying to disable the rounded logs feature on the lighted log from chromaticraft. not sure if i'm just doing it wrong but it isn't working.
i tried putting this(ChromatiCraft.Block.Dimension.BlockLightedLog) which is the block class i think
but it didn't do anything

**Comment by octarine-noise** [comment]
Try **Reika.ChromatiCraft.Block.Dimension.BlockLightedLog**, that's the block class

**Comment by Adraxas** [comment]
thanks, that fixed it
