### ISSUE TITLE
Mixin Bootstrap Crash w/ Immersive Portals

### ISSUE THREAD

**Issue by WenXin20** [octarine-noise/BetterFoliage#270]
`Minecraft v1.14.4`
`Forge v28.1.115`
`Better Foliage v2.5.0`
`Kottle v1.4.0`
`Mixin Bootstrap v1.0.0`
[`Immersive Portals v0.10`](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge)

Since both Immersive Portals & Better Foliage require Mixin Bootstrap to function, I'm getting a crash as soon as I try to start the game. Is this something that can be fixed?
[Crash Log](https://gist.github.com/WenXin20/ecf10e64c1d0420ec4dc1bdf7bb0b869)

**Comment by rtng2** [comment]
I'm also getting the "game crashed" error whenever I put MixinBootstrap in the mod folder (I don't use Immersive Portals). If I remove MixinBootstrap, BetterFoliage will still load, but there are no changes to the game, i.e. no round logs, no changes to the leaves, etc.

**Comment by octarine-noise** [comment]
I need to investigate this further, this is completely new territory for me (1st time using mixins).
@rtng2 what other mods are you using?

**Comment by rtng2** [comment]
```
Forge v28.1.0
Better Foliage v2.5.0
Kottle v1.4.0
Mixin Bootstrap v1.0.0
OptiFine 1.14.4 HD U F5
```
mods folder :
![Untitled](https://user-images.githubusercontent.com/36557067/72672725-3dd10980-3a91-11ea-9bce-b9f699bb4e3a.png)

Well, I haven't tried using Forge v28.1.115 yet, maybe that could be the issue?

**Comment by WenXin20** [comment]
Yeah, your forge is probably outdated. Try providing the crash report too.

**Comment by rtng2** [comment]
Yes you're right, the error disappears when I use Forge v28.1.115.
Just wanna let @octarine-noise know, the mod still looks buggy :

![2020-01-19_08 22 16](https://user-images.githubusercontent.com/36557067/72672964-a3bf9000-3a95-11ea-88fc-73e64b639bf9.png)

**Comment by octarine-noise** [comment]
I hope you have an Nvdia card, because then the answer is simple. Edit the BF config file, and set
`nVidia = true`

It's a bit awkward now, as there is no Forge config GUI yet and for technical reasons I can't autodetect the default setting anymore.

**Comment by rtng2** [comment]
Can you please tell me where BF config file is? Is it \mods\betterfoliage\client\config\Config.class? I'm not proficient in Java and not really sure how to set nVidia = true.

**Comment by WenXin20** [comment]
You don't need to go into the betterfoliage mod jar. Instead go to `.minecraft/config` folder and in there is a file called `betterfoliage-client.toml`.

**Comment by WenXin20** [comment]
@octarine-noise 
Immersive Portals put out v0.11 that fixes the crash, but logs are not round and reeds seem to have a squished texture, it gives an error in chat only that says `betterfoliage.rendererror`. Round logs work if Immersive Portals is removed.

**Comment by octarine-noise** [comment]
@rtng2 the location of the config file is `config/betterfoliage-client.toml` under your instance directory. There will be other directories like `mods,` `saves,` `resourcepacks` etc. under it.

However, where your instance is located depends on which launcher you are using.
In the Mojang launcher, instances are listed under "installations", you can click on the one you're using to edit it, and look at the "game directory" option. (if it says "default" then I give up, I always put my instances into specific directories)

**Comment by octarine-noise** [comment]
@WenXin20 it probably has something to do with Immersive Portals having multiple worlds loaded at the same time on the client. I tried to account for that, but probably overlooked something. I'll come back to fixing it after BF for Fabric comes out.

**Comment by octarine-noise** [comment]
Closing the issue, as the original problem seems to be fixed
