### ISSUE TITLE
TerraFirmaCraft Compatibility

### ISSUE THREAD

**Issue by Kittychanley** [octarine-noise/BetterFoliage#28]
Would you please add the ability to add mod-block support for sand, lily pads and cacti? TerraFirmaCraft has its own versions for these, and therefore the better lily pads, better cactus and coral do not work.

https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Blocks/Vanilla/BlockCustomLilyPad.java
https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Blocks/Vanilla/BlockCustomCactus.java
https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Blocks/Terrain/BlockSand.java

Alternatively, instead of doing block == Blocks.waterlily, you could use block instanceof BlockLilyPad and our lily pads would then work. Our cacti and sand don't extend the vanilla versions though, so those will require alternative matching.

**Comment by octarine-noise** [comment]
Fixed in 1.0.15
