### ISSUE TITLE
Minecraft Crash Report

### ISSUE THREAD

**Issue by PragmaticWisdom** [octarine-noise/BetterFoliage#29]
Hi Octarine-noise, I have recently downloaded your mod and it has just crashed my game, here is the crash report as requested. I am sorry for the massive wall of text, I am unsure if this site supports spoilers...

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-mc1.8-1.1.5.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 4/08/15 5:38 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:588)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:583)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:459)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1081)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.GuiScreen.func_146270_b(GuiScreen.java:588)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:583)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:459)

-- Screen render details --
Details:
	Screen name: de.eydamos.backpack.gui.GuiBackpack
	Mouse location: Scaled: (298, 125). Absolute: (427, 240)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['PragmaticWisdom'/251, l='MpServer', x=-28.65, y=74.00, z=225.43]]
	Chunk stats: MultiplayerChunkCache: 438, 438
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 84.00,64.00,252.00 - World: (84,64,252), Chunk: (at 4,4,12 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 682292 game time, 77983 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 105 total; [EntitySkeleton['Skeleton'/557581, l='MpServer', x=10.50, y=13.00, z=268.50], EntitySkeleton['Skeleton'/557582, l='MpServer', x=8.50, y=13.00, z=269.50], EntityZombie['Zombie'/557583, l='MpServer', x=44.50, y=40.00, z=227.50], MoCEntityRaccoon['Raccoon'/15, l='MpServer', x=-97.53, y=68.00, z=186.31], MoCEntityRaccoon['Raccoon'/16, l='MpServer', x=-98.31, y=67.00, z=189.91], EntityZombie['Zombie'/552216, l='MpServer', x=43.50, y=22.00, z=228.50], MoCEntityRaccoon['Raccoon'/17, l='MpServer', x=-108.38, y=68.00, z=190.59], MoCEntityDeer['Deer'/279, l='MpServer', x=-137.59, y=62.56, z=294.44], EntityZombie['Zombie'/557584, l='MpServer', x=45.50, y=40.00, z=229.50], MoCEntityMaggot['Maggot'/26, l='MpServer', x=-96.53, y=64.00, z=245.19], EntityCreeper['Creeper'/557587, l='MpServer', x=-33.25, y=38.00, z=277.06], MoCEntityDuck['Duck'/284, l='MpServer', x=-156.63, y=74.00, z=130.31], MoCEntityDeer['Deer'/29, l='MpServer', x=-100.75, y=74.00, z=321.09], EntitySpider['Spider'/557589, l='MpServer', x=-55.50, y=63.00, z=195.50], MoCEntityEnt['Ent'/286, l='MpServer', x=-125.44, y=79.00, z=101.91], EntityZombie['Zombie'/552214, l='MpServer', x=3.50, y=36.00, z=288.50], EntityZombie['Zombie'/551703, l='MpServer', x=-11.50, y=57.00, z=273.50], EntitySheep['Sheep'/33, l='MpServer', x=-91.28, y=64.00, z=151.38], EntitySheep['Sheep'/36, l='MpServer', x=-94.56, y=66.00, z=162.41], EntitySheep['Sheep'/37, l='MpServer', x=-91.13, y=67.00, z=165.38], EntitySheep['Sheep'/38, l='MpServer', x=-86.19, y=66.00, z=171.81], MoCEntityEnt['Ent'/295, l='MpServer', x=-153.03, y=74.00, z=113.09], EntitySheep['Sheep'/39, l='MpServer', x=-86.09, y=63.00, z=175.50], EntityDuck['Duck'/41, l='MpServer', x=-83.75, y=64.00, z=185.56], MoCEntityRaccoon['Raccoon'/42, l='MpServer', x=-90.53, y=64.00, z=181.75], EntityDuck['Duck'/43, l='MpServer', x=-89.19, y=62.47, z=211.91], EntitySpider['Spider'/547619, l='MpServer', x=-20.50, y=26.00, z=203.50], MoCEntityMaggot['Maggot'/46, l='MpServer', x=-94.28, y=64.00, z=245.25], MoCEntityMaggot['Maggot'/47, l='MpServer', x=-94.84, y=64.00, z=243.50], MoCEntityDeer['Deer'/48, l='MpServer', x=-82.47, y=67.00, z=242.84], MoCEntityMaggot['Maggot'/49, l='MpServer', x=-95.50, y=64.00, z=245.50], EntityEnderman['Enderman'/553274, l='MpServer', x=0.69, y=57.00, z=265.28], MoCEntityFishy['Fishy'/54, l='MpServer', x=-64.28, y=62.00, z=107.13], EntityCreeper['Creeper'/553267, l='MpServer', x=-16.00, y=26.00, z=299.56], EntityEnderman['Enderman'/550964, l='MpServer', x=9.50, y=30.02, z=236.50], EntitySheep['Sheep'/61, l='MpServer', x=-78.22, y=64.00, z=166.06], MoCEntityDeer['Deer'/62, l='MpServer', x=-83.47, y=66.00, z=253.47], EntityEnderman['Enderman'/550966, l='MpServer', x=9.50, y=30.02, z=237.50], EntityPlayerSP['PragmaticWisdom'/251, l='MpServer', x=-28.65, y=74.00, z=225.43], EntityZombie['Zombie'/528461, l='MpServer', x=28.50, y=35.00, z=277.88], EntitySpider['Spider'/559949, l='MpServer', x=-1.50, y=23.00, z=286.50], EntityZombie['Zombie'/528462, l='MpServer', x=22.50, y=36.00, z=281.94], EntityItem['item.item.egg'/557379, l='MpServer', x=-84.28, y=64.00, z=185.94], EntityCreeper['Creeper'/542276, l='MpServer', x=38.50, y=12.00, z=220.50], EntityDuck['Duck'/84, l='MpServer', x=-42.56, y=69.00, z=265.63], EntityCreeper['Creeper'/459602, l='MpServer', x=-36.56, y=63.00, z=252.00], MoCEntityDeer['Deer'/86, l='MpServer', x=-41.47, y=67.00, z=271.50], MoCEntityWerewolf['Werewolf'/560724, l='MpServer', x=60.50, y=28.00, z=236.50], MoCEntityWerewolf['Werewolf'/560725, l='MpServer', x=58.50, y=28.00, z=235.50], MoCEntitySnail['Snail'/94, l='MpServer', x=-27.34, y=66.00, z=128.31], MoCEntityRaccoon['Raccoon'/105, l='MpServer', x=9.38, y=66.00, z=115.38], EntityZombie['Zombie'/523881, l='MpServer', x=-70.50, y=33.00, z=157.50], EntitySkeleton['Skeleton'/562552, l='MpServer', x=-64.50, y=39.02, z=168.50], MoCEntityWerewolf['Werewolf'/545657, l='MpServer', x=15.44, y=33.00, z=309.59], EntityZombie['Zombie'/559228, l='MpServer', x=-30.50, y=42.00, z=248.50], EntityCreeper['Creeper'/562556, l='MpServer', x=-14.50, y=55.02, z=274.50], MoCEntityWerewolf['Werewolf'/525174, l='MpServer', x=-97.94, y=23.00, z=168.22], EntityItem['item.item.fish.cod.raw'/531851, l='MpServer', x=24.03, y=34.00, z=288.88], EntityItem['item.item.fish.cod.raw'/531852, l='MpServer', x=19.66, y=34.00, z=288.69], EntitySpider['Spider'/477588, l='MpServer', x=-42.72, y=77.09, z=224.50], EntitySkeleton['Skeleton'/557467, l='MpServer', x=19.50, y=42.00, z=223.50], EntitySheep['Sheep'/148, l='MpServer', x=29.53, y=63.00, z=283.47], EntitySheep['Sheep'/149, l='MpServer', x=30.41, y=70.00, z=284.88], EntitySkeleton['Skeleton'/562077, l='MpServer', x=-61.50, y=12.00, z=296.50], EntitySheep['Sheep'/150, l='MpServer', x=31.78, y=70.00, z=283.63], MoCEntityMediumFish['MediumFish'/151, l='MpServer', x=31.06, y=62.41, z=322.69], EntityFish['Fish'/557968, l='MpServer', x=-66.53, y=60.94, z=144.97], EntitySkeleton['Skeleton'/496798, l='MpServer', x=-27.31, y=49.02, z=216.69], EntityFish['Fish'/557969, l='MpServer', x=-68.31, y=59.53, z=149.34], EntityTropiFish['Tropical Fish'/547988, l='MpServer', x=-9.47, y=61.04, z=237.85], EntityTropiFish['Tropical Fish'/547989, l='MpServer', x=-9.04, y=61.01, z=245.88], MoCEntityRaccoon['Raccoon'/158, l='MpServer', x=45.16, y=64.00, z=116.53], EntityTropiFish['Tropical Fish'/547990, l='MpServer', x=0.19, y=59.00, z=236.59], MoCEntityRaccoon['Raccoon'/160, l='MpServer', x=38.06, y=64.00, z=135.28], EntityItem['item.item.egg'/550312, l='MpServer', x=-43.06, y=69.00, z=265.41], EntitySheep['Sheep'/162, l='MpServer', x=33.44, y=67.00, z=286.06], MoCEntityDeer['Deer'/163, l='MpServer', x=40.84, y=70.00, z=267.50], MoCEntitySmallFish['SmallFish'/164, l='MpServer', x=37.06, y=62.41, z=300.28], MoCEntitySmallFish['SmallFish'/165, l='MpServer', x=42.56, y=62.00, z=312.31], MoCEntityWerewolf['Werewolf'/559279, l='MpServer', x=44.69, y=21.00, z=219.44], MoCEntityRaccoon['Raccoon'/169, l='MpServer', x=48.75, y=64.00, z=130.75], MoCEntityBear['Bear'/170, l='MpServer', x=58.84, y=66.00, z=143.91], MoCEntityShark['Shark'/171, l='MpServer', x=40.50, y=62.00, z=183.06], MoCEntityDeer['Deer'/173, l='MpServer', x=47.50, y=65.00, z=216.53], MoCEntityDeer['Deer'/174, l='MpServer', x=58.84, y=63.00, z=250.56], MoCEntityMediumFish['MediumFish'/175, l='MpServer', x=49.53, y=62.00, z=278.91], MoCEntityRaccoon['Raccoon'/178, l='MpServer', x=68.84, y=63.00, z=124.88], EntityZombie['Zombie'/547770, l='MpServer', x=-43.50, y=52.00, z=221.09], EntityZombie['Zombie'/547771, l='MpServer', x=-39.53, y=52.00, z=214.09], EntityItem['item.item.sulphur'/535740, l='MpServer', x=-33.66, y=55.00, z=213.13], EntitySpider['Spider'/524976, l='MpServer', x=-46.31, y=52.09, z=229.28], MoCEntityWerewolf['Werewolf'/559280, l='MpServer', x=45.47, y=23.00, z=220.53], MoCEntityDeer['Deer'/185, l='MpServer', x=83.44, y=63.00, z=186.47], MoCEntityWerewolf['Werewolf'/559283, l='MpServer', x=46.94, y=23.00, z=221.50], MoCEntityWerewolf['Werewolf'/545205, l='MpServer', x=-141.50, y=26.00, z=196.50], MoCEntityFishy['Fishy'/195, l='MpServer', x=90.84, y=62.00, z=311.84], EntityCreeper['Creeper'/430286, l='MpServer', x=-14.28, y=61.53, z=225.84], EntityZombie['Zombie'/536001, l='MpServer', x=25.88, y=66.00, z=206.56], EntityItem['item.item.rottenFlesh'/542149, l='MpServer', x=29.41, y=71.00, z=202.16], MoCEntityFlameWraith['FlameWraith'/549854, l='MpServer', x=-11.75, y=41.50, z=130.25], EntityCreeper['Creeper'/548325, l='MpServer', x=-11.50, y=72.00, z=271.50], MoCEntityWerewolf['Werewolf'/551930, l='MpServer', x=-92.09, y=30.00, z=288.22], EntityItem['item.item.feather'/546555, l='MpServer', x=-90.25, y=60.00, z=211.88], MoCEntityDeer['Deer'/252, l='MpServer', x=-117.13, y=64.00, z=216.81], MoCEntityDeer['Deer'/254, l='MpServer', x=-107.59, y=64.00, z=252.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2503)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 358273648 bytes (341 MB) / 889765888 bytes (848 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 4, tcache: 0, allocated: 13, tallocated: 91
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1502 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1502.jar) 
	UCHIJAAAA	Forge{11.14.3.1502} [Minecraft Forge] (forge-1.8-11.14.3.1502.jar) 
	UCHIJAAAA	ChickenShed{1.1.4} [Chicken Shed] ([1.8] ChickenShed (v1.2.0).jar) 
	UCHIJAAAA	animalsplus{1.3} [Animals Plus] (animalsplus-1.3.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.8.x.jar) 
	UCHIJAAAA	Batty's Coordinates PLUS{1.8.0_1.7.0} [Batty's Coordinates PLUS Mod for Forge] (Batty's Coordinates PLUS Mod for Forge-1.8.0_1.7.0.jar) 
	UCHIJAAAA	BetterFoliage{1.1.5} [Better Foliage] (BetterFoliage-mc1.8-1.1.5.jar) 
	UCHIJAAAA	BetterLeather{2.0} [Better Leather] (BetterLeather-universal-1.8-2.1.0.jar) 
	UCHIJAAAA	convenient_recipes{1.8-1.6} [Convenient Recipes] (ConvenientRecipes-1.8-1.6.jar) 
	UCHIJAAAA	darkroleplay{0.2.0 } [§4§nDark Roleplay] (Dark Roleplay v0.2.3b - Alpha.jar) 
	UCHIJAAAA	decorationmegapack{1.18} [Decoration Mega Pack] (decorationmegapack-1.18-1.8-1446.jar) 
	UCHIJAAAA	dessertcraft{v1.4} [Dessertcraft] (Dessertcraft-1.4.jar) 
	UCHIJAAAA	doggytalents{v1.9.1g} [Doggy Talents] (DoggyTalents-1.8-v1.9.1g-universal.jar) 
	UCHIJAAAA	MoCreatures{8.0.0.devA} [DrZhark's Mo'Creatures Mod] (DrZhark's Mo'Creatures Mod-8.0.0.devA.jar) 
	UCHIJAAAA	extrafood{v1.1} [Extra Food Mod] (ExtraFood-1.1.jar) 
	UCHIJAAAA	ftea{1.8b} [Flower Tea] (Flower Tea 1.8b.jar) 
	UCHIJAAAA	fulcrum{2.0.2.0} [FULCRUM] (FULCRUM 2.0.2.0.jar) 
	UCHIJAAAA	fyberbackpack{1.0} [Just Backpacks] (justbackpacks-mc1.8-1.0.jar) 
	UCHIJAAAA	magicyarn{1.1.6} [Magic Yarn] (MagicYarn-1.8.jar) 
	UCHIJAAAA	RadixCore{2.0.3-1.8} [RadixCore] (RadixCore-2.0.3-1.8-universal.jar) 
	UCHIJAAAA	MCA{5.0.6.1-1.8} [Minecraft Comes Alive] (MCA-5.0.6.2-1.8-universal.jar) 
	UCHIJAAAA	cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8-build1(1.8).jar) 
	UCHIJAAAA	PetBat{1.3.9} [Pet Bat] (PetBat-1.8.jar) 
	UCHIJAAAA	plantmegapack{5.07} [Plant Mega Pack] (plantmegapack-5.07-1.8-1446.jar) 
	UCHIJAAAA	SophisticatedWolves{3.5.0} [SophisticatedWolves] (SophisticatedWolves-3.5.0.jar) 
	UCHIJAAAA	wormsmod{1.1.1} [Worms Mod] (wormsmod-1.8.x-1.1.1.jar) 
	UCHIJAAAA	zombie_steak{1.8-1.0.2} [Zombie Steak] (ZombieSteak-1.8-1.0.2.jar) 
	Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-mc1.8-1.1.5.jar)
  mods.betterfoliage.loader.impl.BetterFoliageTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce GTS 250/PCIe/SSE2'
	Launched Version: 1.8-Forge11.14.3.1502
	LWJGL: 2.9.1
	OpenGL: GeForce GTS 250/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

If there is anything you might be able to help me with this crash, I would be most thankful.
Regards,
PragmaticWisdom

**Comment by octarine-noise** [comment]
According to the section *Screen render details*, the problem is with the Backpack mod
