### ISSUE TITLE
Foliage missing, no visuals

### ISSUE THREAD

**Issue by Triliton** [octarine-noise/BetterFoliage#295]
Im running MC 1.14.4 and  Forge 28.1.0, OptiFine_1.14.4_HD_U_F4,  Kottle 1.4.0, Minobootstrap 1.0.0 and Better Foliage 2.5.0

I have no foliage, nor anything from the mod. 
The config file is there, and everything is enabled.
Ive even tried adding in an older config file, still same results.

**Comment by Triliton** [comment]
I have changed Forge version to 28.1.96, still same results. 

No foliage

**Comment by VonZeeple** [comment]
As specified in the description page: 

> Version 2.5.x for Forge requires Kottle and MixinBootstrap

Have you downloaded MixinBootstrap?

**Comment by Triliton** [comment]
> As specified in the description page:
> 
> > Version 2.5.x for Forge requires Kottle and MixinBootstrap
> 
> Have you downloaded MixinBootstrap?

Look in my issue: yes  Maxinbootstrap 1.0.0

**Comment by Triliton** [comment]
After re-downloading the mods, upgrading my Nvidia graphics and re-setting Minecraft video settings it works. Thanks VonZeeple for reminding me of my issue :)
