### ISSUE TITLE
TFC Round Log inconsistencies

### ISSUE THREAD

**Issue by Bunsan** [octarine-noise/BetterFoliage#31]
For the TFC round log support there are some inconsistencies and issues.  

In TFC all trees are 1x1 with exception of the sequoia and kapok, which are 2x2 trees.  There are 17 tree types in 2 classes (I may be using that term wrong, not a programmer). All trees with exception of acacia are located in the one class (com.bioxx.tfc.Blocks.Flora.BlockaLogNatural, com.bioxx.tfc.Blocks.Flora.BlockaLogVert, com.bioxx.tfc.Blocks.Flora.BlockaLogHoriz) and acacia is located in (com.bioxx.tfc.Blocks.Flora.BlockaLogNatural2, com.bioxx.tfc.Blocks.Flora.BlockaLogVert2, com.bioxx.tfc.Blocks.Flora.BlockaLogHoriz2). All TFC trees with exception of acacia do not get the connected texture. I understand the mod does not have the functionality to limit the connected texture for each tree, but perhaps allowing the main log classes to have connected textures would be appropriate.

**Comment by octarine-noise** [comment]
Could you post a screenshot to illustrate the issue? I don't quite understand what's going on with the textures.

**Comment by Bunsan** [comment]
Sorry for the Delay.

http://i.imgur.com/JU1rUAn.png

So these are constructed with blocks from the BlockaLogNatural and BlockaLogNatural2, but the BlockaLogVert and BlockaLogVert2 classes do the same thing. The difference between these blocks in game is that a tree growing places the BlockaLogNatural/2 class whereas a player placed log is the BlockaLogVert/2 class.

So I was wrong in that the logs with a meta value of 0-3 do have the connected texture.The two sets in blue squares are the 2x2 trees. I know this has to do with how Minecraft and likely most other mods deal with log blocks (0-3 being vertical etc.) Not sure if easily fixable, but hopefully this makes more sense now.

**Comment by octarine-noise** [comment]
Ah, I see now. I only added the new code in one place (detecting log direction), but forgot in another (detecting neighbor log directions). So in the cases where the meta is incompatible with the vanilla way, the renderer wrongly believes the neighbors point in the wrong direction to connect.
