### ISSUE TITLE
Strange behavior with Candelabra from Witchery mod.

### ISSUE THREAD

**Issue by Unknown-Zombie** [octarine-noise/BetterFoliage#32]
Something about the 1.7.10-1.0.15 version is trying to apply what looks like a lily pad to Witchery's Candelabra. This wasn't present in 1.7.10-1.0.14. Downgrading to 1.7.10-1.0.14 fixes the issue.

When looking at the Candelabra sitting on a table there is some kind of strange texture on the bottom, with what looks like a pink lily pad flower in the middle. When you place the Candelabra high against a wall, you can see that it looks like there are lily pad roots coming from the bottom.

![Imgur](http://i.imgur.com/KNsah1R.png)
![Imgur](http://i.imgur.com/AiAW31p.png)

**Comment by octarine-noise** [comment]
Does the problem still come up with 2.0?
