### ISSUE TITLE
[1.16.5] Crash with Abnormals Core

### ISSUE THREAD

**Issue by Raithion** [octarine-noise/BetterFoliage#325]
Mods used:
- Better Foliage **2.6.1**
- Abnormals Core **3.1.1**
- Kotlin for Forge **1.12.0**

https://pastebin.com/G2fSwBNH

Only occurs with Better Foliage installed. Abnormals Core and Kotlin work fine together otherwise.

**Comment by octarine-noise** [comment]
Fixed in 2.6.2
