### ISSUE TITLE
1.16.5. Disabling rounded logs for version

### ISSUE THREAD

**Issue by gordrhain** [octarine-noise/BetterFoliage#328]
Rounded wood creates a lot of trouble in terms of appearance when building. Is there a solution to this?

**Comment by octarine-noise** [comment]
Yes, you can turn them off.

If you're using Fabric, click "Mods" in the main menu, find Better Foliage in the list on the left, then click the small "Configure" button in the top right. In the category "Round Logs", turn "enabled" to "no".

With Forge, it's a bit more difficult, as there's no GUI for the config in newer versions (which I assume you are using). You must first find your config directory. I can't help you with that, this part depends on what launcher you're using. Once there, open the file `betterfoliage-client.toml` in a text editor, find the category `[roundLogs]`, and change `enabled = true` to `enabled = false`.

**Comment by octarine-noise** [comment]
FYI, the most recent version (2.5.2 or 2.6.4) has a configuration GUI if you also have Cloth Config installed.
