### ISSUE TITLE
Not compatible with OptiFine D5

### ISSUE THREAD

**Issue by CGsama** [octarine-noise/BetterFoliage#33]
![2015-11-08_21 52 32](https://cloud.githubusercontent.com/assets/15722562/11024924/4876b786-8663-11e5-8aef-81bc7f33c104.png)

I tried turn off AF and AA, but the problem still. Uninstall OptiFine will working normally.  
MineCraft_1.8, Forge_1480, OptiFine_U_D5, BetterFoliage_1.1.7

Thank you.

**Comment by Skylerh101** [comment]
Yeah I have experienced this same issue.

**Comment by octarine-noise** [comment]
I could not reproduce the issue with the given versions, or more recent versions (Forge 1563, Optifine U F8), in any combination, which makes it borderline impossible to bugfix...
I'll try sifting through OptiFine's code to figure it out. In the meantime, could you try messing with your video settings, and try to make it go away?

**Comment by CGsama** [comment]
[options.txt](https://github.com/octarine-noise/BetterFoliage/files/49579/options.txt)
[optionsof.txt](https://github.com/octarine-noise/BetterFoliage/files/49580/optionsof.txt)
Here is my sitting file!
I try to upgrade OptiFine to G6 but problem still :(

**Comment by octarine-noise** [comment]
Does the problem still come up with 2.0 and Optifine G9?

**Comment by CGsama** [comment]
![2016-01-13_21 21 26](https://cloud.githubusercontent.com/assets/15722562/12314061/bcf2a992-ba3b-11e5-8474-35ffc121fa17.png)

**Comment by CGsama** [comment]
G9 with 2.0.1, all works! but can't  turn on AF and AA

**Comment by CGsama** [comment]
both off
![2016-01-13_21 36 21](https://cloud.githubusercontent.com/assets/15722562/12314290/d1a80ed4-ba3d-11e5-9286-5df2d6c52b07.png)
AF on
![2016-01-13_21 36 07](https://cloud.githubusercontent.com/assets/15722562/12314295/daff014a-ba3d-11e5-92f1-deeacb75dcdc.png)
AA on
![2016-01-13_21 37 49](https://cloud.githubusercontent.com/assets/15722562/12314312/fad388f6-ba3d-11e5-93d1-e59ffed95330.png)
Both on
![2016-01-13_21 38 34](https://cloud.githubusercontent.com/assets/15722562/12314317/09c7f14e-ba3e-11e5-8c2f-c7b41d0ae3df.png)

**Comment by Plazma7** [comment]
The same thing happens to me, and it's very annoying. If this could be fixed, that would be great. I love this mod, but I need optifine for certain things.

**Comment by octarine-noise** [comment]
Incompatibility with anisotropic filtering is a known issue, which will get fixed... eventually.

**Comment by Inve1951** [comment]
having the same issue on 1.10.2 still
