### ISSUE TITLE
Soul Sand rising soul texture is missing

### ISSUE THREAD

**Issue by Foozey** [octarine-noise/BetterFoliage#332]

**Comment by EternalOne11** [comment]
also having this problem. (may be a performance mod but I have not tested in-depth yet.

**Comment by Kaleidio** [comment]
Optifine G8 causes the issue, which is a regression from Optifine G7 that works fine.  Strange.

**Comment by NighthowlerStudios** [comment]
Also, duplicate of #330

**Comment by Foozey** [comment]
I'm not using shaders, so it's not a shader-only thing.

**Comment by NighthowlerStudios** [comment]
interesting.  but are you using Optifine?

**Comment by Foozey** [comment]
Yeah, G8 like you mentioned, but I just wanted to clarify for development purposes that it's not a shader-specific issue, since I'm not using them.

**Comment by bbharier** [comment]
I see this too, and am indeed using Optifine.

Also I have a modern AMD graphics card, as opposed to Nvidia which seems to be more common still. Doubtful that would be a factor for something like this, but with Optifine's accelerated rendering who knows.

**Comment by octarine-noise** [comment]
Fixed in 2.6.5
