### ISSUE TITLE
multiplayer menu red x

### ISSUE THREAD

**Issue by ghost** [octarine-noise/BetterFoliage#334]
Servers get labeled as incompatible when the server is not running BetterFoliage. I don't think this is intended because I'm pretty sure that BetterFoliage is meant to be a client-side mod.

from client latest.log
`[20May2021 16:30:50.130] [Netty Client IO #7/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [betterfoliage]`

**Comment by octarine-noise** [comment]
Weird, I can connect to a server without BF, no problem.

Can you post the full crashlog somewhere, like mclo.gs or gist?

**Comment by octarine-noise** [comment]
Ok, I found something that *might* have prevented you from connecting, but I'm not sure as it was working fine for me.

You issue is very likely fixed by 2.5.2 or 2.6.4 (depending on your MC version). If not, please reopen the issue and provide more details.
