### ISSUE TITLE
zh_cn.json added one more comma, which should be deleted

### ISSUE THREAD

**Issue by XiLaiTL** [octarine-noise/BetterFoliage#339]
Sorry that I had forgotten to upload the json and am glad to see your work to add it in the new version.
However, I thought that a more comma was added in the last line making the Chinese lang file invalid.

So, I think the additional comma should be deleted.
Here is the screenshot
![file](https://user-images.githubusercontent.com/20791912/119248211-37d9c400-bbc2-11eb-9c32-9b7b2dc8cd6d.png)

**Comment by octarine-noise** [comment]
Whoops. Thanks for the heads-up, I'll correct it.

And thanks for the translation!

**Comment by octarine-noise** [comment]
Fixed in 2.6.5
