### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by NanoCE** [octarine-noise/BetterFoliage#34]
I have a block not rendering underneath a grass block. I do have optifine and better foliage. I am playing with the latest 1.7 release....

**Comment by octarine-noise** [comment]
Does the problem still come up with 2.0?

**Comment by NanoCE** [comment]
No it does not. 

If you do want to know though is that the cause for this was a mod called iskall minimobs. But since the new better foliage worked im all good!
