### ISSUE TITLE
Opening resource pack selection screen causes crash with better foliage installed (fabric 1.16.5)

### ISSUE THREAD

**Issue by sucroseMC** [octarine-noise/BetterFoliage#341]
https://gist.githubusercontent.com/natanfudge/f1b964b420bcc1922a9c36aed945dd8a

**Comment by sucroseMC** [comment]
changed the title because i'm stupid

**Comment by WatermelonArray** [comment]
Can confirm this happens as well. When uninstalling the mod, I can open the resource pack screen.

**Comment by silvigon** [comment]
Confirming here as well.

**Comment by octarine-noise** [comment]
Fixed in 2.6.5
