### ISSUE TITLE
Inconsistent textures on rounded logs

### ISSUE THREAD

**Issue by LolJohn11** [octarine-noise/BetterFoliage#343]
The "top" of a wooden log is rounded to an octagon, while the "body" of a log is rounded to a hexagon, making the place where they connect display with missing polygons. Seems to affect all of the logs that are rounded.

![2021-05-28_15 42 03](https://user-images.githubusercontent.com/49366383/119985428-4b729980-bfcb-11eb-8cf5-9b7089a90b8b.png)
![2021-05-28_15 42 14](https://user-images.githubusercontent.com/49366383/119985434-4ca3c680-bfcb-11eb-9b03-76a57f18c4c8.png)
![2021-05-28_15 47 57](https://user-images.githubusercontent.com/49366383/119986235-4530ed00-bfcc-11eb-9c4d-d73962bb4154.png)

**Comment by LolJohn11** [comment]
It seems that the issue resolved itself somehow.

**Comment by octarine-noise** [comment]
This has to do with the value *nVidia* in the config.
You have to set this value to true if you have an Nvidia GPU, as there are differences in how they render stuff, and I haven't found a way to reliably set this at startup.
It's possible you accidentally set this value, and the problem went away.
