### ISSUE TITLE
Weird glitch with campfires (1.16.5)

### ISSUE THREAD

**Issue by E-daw** [octarine-noise/BetterFoliage#349]
Hello,
This isn't very long but better foliage has been messing with campfires a bit. 

I saw a comment on the main curseforge page about it also messing with other "non-full" blocks according to some user. I haven't really seen anything else but idk.

![2021-06-01_20 32 20](https://user-images.githubusercontent.com/34014927/120410379-7c7b0300-c318-11eb-9bd1-da9e544e056c.png)

Version 2.6.4 for Forge

**Comment by octarine-noise** [comment]
Fixed in 2.6.5
