### ISSUE TITLE
Could not initialize class mods.betterfoliage.BetterFoliageMod

### ISSUE THREAD

**Issue by astroACR** [octarine-noise/BetterFoliage#359]
I have a modpack with a little over 100+ mods, all of which worked fine until yesterday when the game decided to not start at all. It gets stuck in the boot sequence and stays there, forever. If I try to do anything the game closes and shows me a crash log "Could not initialize class mods.betterfoliage.BetterFoliageMod". This leads me to believe it's an issue with this mod, in particular, hope I can get some help.

https://pastebin.com/iyCnRiSK

**Comment by octarine-noise** [comment]
Better Foliage is currently not compatible with Sodium.
I'm closing this for now, as Sodium support is on the (very) long-term roadmap.
