### ISSUE TITLE
Falling leaf mappings not working (BF2.0 / MC1.8)

### ISSUE THREAD

**Issue by HanPrower** [octarine-noise/BetterFoliage#36]
I've read and re-read the "how to" page and it doesn't appear to have changed since last I used the mod, but the mappings seem to be refusing to work properly. Every tree just drops birch leaves.

I'm using:
BetterFoliage-MC1.8-2.0
Forge 11.4.14.1563

This is my leafTextureMappings.cfg file (located in /assets/betterfoliage/):

```
// Fully qualify the mapping in case of name clashes with mods
// Mod is mod's texture folder not ModID || after : is partial (or full match) to leaf texture name

// Vanilla
minecraft:acacia=birch
minecraft:birch=birch
minecraft:spruce=spruce
minecraft:jungle=jungle
minecraft:oak=oak
```

And some of the /assets/betterfoliage/textures/blocks folder:
![blocks folder](http://puu.sh/mrZg3/fb199c628f.png)

I'm not sure if this is related or just an unhappy aside, but if the resources are reloaded with F3+T or a resourcepack is changed whilst the game is open BF falling leaf particles get messed up entirely and they choose totally random textures from the atlas (such as grass, etc.).

**Comment by octarine-noise** [comment]
Yeah, I missed that one. Fix coming soon.

**Comment by HanPrower** [comment]
@octarine-noise, whilst you've fixed the reload corruption the actual mappings still don't seem to work.

**Comment by octarine-noise** [comment]
Derp.
