### ISSUE TITLE
Better Foliage and Sodium

### ISSUE THREAD

**Issue by Singularitaet99** [octarine-noise/BetterFoliage#360]
### Reproduction Steps
Download both:
Sodium forge
And Better Foliage forge

### Crash Report File

https://github.com/Pannoniae/sodium-forge/files/6493546/latest.log

### Additional Information
I'm not sure if that's a known issue but I just wanted to let you know that Better foliage crashes when used together with Sodium forge. I'm sorry if it's not on your side. Let me know if that's the case.
It would be nice if there was a way to fix this... if not please let me know it anyway.
Thank you!
It might be a sodium issue idk.

**Comment by octarine-noise** [comment]
Better Foliage is currently not compatible with Sodium.
I'm closing this for now, as Sodium support is on the (very) long-term roadmap.
