### ISSUE TITLE
Grass Colour not working for TFC

### ISSUE THREAD

**Issue by Bunsan** [octarine-noise/BetterFoliage#37]
BetterFoliage-MC1.7.10-2.0.1
TFC Beta 0.79.27.903
Forge 1566

When connected grass and short grass are enabled the textures have no colour. For the connected grass it is only the top texture that is colourless.

Both connected grass and short grass http://i.imgur.com/xno1oA2.png

Just short grass. http://i.imgur.com/CJxlXIz.png

**Comment by octarine-noise** [comment]
Fixed the color issue in 2.0.3.

Connected grass cannot be used with TFC, but is unnecessary anyway.
