### ISSUE TITLE
Better Foliage makes the tree leaves look weird.

### ISSUE THREAD

**Issue by DeceptionDeceives** [octarine-noise/BetterFoliage#376]
![image](https://user-images.githubusercontent.com/87446390/125702877-62a9524c-7d9a-44a7-906a-56415eb16880.png)

I suspect its Better Foliage. This started happening for me on the 1.16.5 version of Minecraft.

**Comment by octarine-noise** [comment]
Sooo... I guess you changed Graphics: Fast to Graphics: Fancy, and it got fixed.

In the next version, leaves will be compatible with Fast Graphics too. Although I really recommend always playing with Fancy graphics and Smooth Shading on. You're already installing visual enhancement mods, why not go all the way?

**Comment by DeceptionDeceives** [comment]
Haha yeah that was the problem. I honestly had no clue about the grass
option thing. I shall try, thank you for creating this epic mod! 😈😈😈
