### ISSUE TITLE
Shader wave effect & transparent animation toggle problem [Forge 1.12.2]

### ISSUE THREAD

**Issue by BenYangOvO** [octarine-noise/BetterFoliage#377]
Recently I'm planning to create a machinima with _Blockbuster_ mod, which is only available on 1.12.2, so in order to make some effects like falling leaves, I could only use BetterFoliage mod in this version. But after installing BetterFoliage, the **leaf waving effects** in any shader which have their own _block.properties_ files couldn’t display normally… I have done what is mentioned in the tips of BetterFoliage’s Mod Settings, but it still doesn’t work, though I have tried to remove all other mods except _Optifine_.

And also, is there any way to toggle off the **transparent animation** which takes place after the leaves fallen down on the ground?

**Comment by octarine-noise** [comment]
Leaf particle fade-out is not currently toggleable. It didn't seem like a big issue, but if that's a dealbreaker for you, I can put out a hotfix, it's a fairly small code change.

Leaf & grass wind effects are working fine for me. I'll give you an example you can check out, and see for yourself where the numbers are coming from:
Shader: Sildur's Vibrant Shaders, High (1.283)
Leaves ID: 10018
Grass ID: 10031

Or, if the shaderpack you use is publicly available, you can also give me a link and I'll tell you the numbers.

**Comment by BenYangOvO** [comment]
> Leaf & grass wind effects are working fine for me. I'll give you an example you can check out, and see for yourself where the numbers are coming from:
> Shader: Sildur's Vibrant Shaders, High (1.283)
> Leaves ID: 10018
> Grass ID: 10031
------------------------------------------------------------------------------------------------------------------------------
I found that the reason I mentioned "Any" above is because every time I switch shaders belong to the BSL series... If I switch between Sildurs or SEUS shaders, there is no problem with the leaves. Now should I modify the shader file or modify the settings in the mod?

**Comment by octarine-noise** [comment]
You should modify the mod settings.

Here are the relevant lines from BSL's `block.properties`:
```
block.10100=minecraft:grass minecraft:fern minecraft:seagrass minecraft:crimson_roots minecraft:warped_roots minecraft:nether_sprouts
block.10105=minecraft:oak_leaves minecraft:spruce_leaves minecraft:birch_leaves minecraft:jungle_leaves minecraft:acacia_leaves minecraft:dark_oak_leaves
```
Leaves ID = 10105
Grass ID = 10100

**Comment by BenYangOvO** [comment]
> You should modify the mod settings.
> Leaves ID = 10105
> Grass ID = 10100
--------------------------------------------------------------------------------------------------------------------------
Thanks very much! And I think I still need the hotfix. But if there's no time finishing the code changes, it’s actually fine. After all, the problem I have is just the fade-out of the leaves will **_cause a white background_** instead of a transparent animation due to the shader.

**Comment by octarine-noise** [comment]
No prob.
Leaf particle fade-out was actually completely fine for me with the BSL shaderpack, but there could be all kinds of differences from one GPU to the next, I don't really understand shaders that much.
I can do the fix tomorrow.

**Comment by octarine-noise** [comment]
[Ninja update](https://www.curseforge.com/minecraft/mc-mods/better-foliage/files/3393955)

The config option is called `fadeOut`
