### ISSUE TITLE
Support for Agricultural Revolution Mod

### ISSUE THREAD

**Issue by WenXin20** [octarine-noise/BetterFoliage#39]
Can you add support for the tangle logs in this mod if it's possible? Thanks

**Comment by octarine-noise** [comment]
Added to the whitelist in 2.0.3.

As tangle logs have no discernible orientation, in order to actually make them render as round, enable the config option **Round Logs / Default to vertical**

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by WenXin20** [comment]
The palm logs from cooking plus don't seem to be round in 2.0.3 by default.
