### ISSUE TITLE
Issue with IC2 trees

### ISSUE THREAD

**Issue by Kanol** [octarine-noise/BetterFoliage#43]
IC2 rubber wood is doesn't display correctly if it have a rubber drop. If it in the begining(first blosk from the dirt) it looks normal, but if it isn't first, it looks uncorrect. IC2 2.2.811 BF 2.0.3 minecraft 1.7.10
![2016-01-31_14 16 34](https://cloud.githubusercontent.com/assets/10697310/12701263/e14f57e8-c825-11e5-9d67-e14288d12494.png)
![2016-01-31_14 16 48](https://cloud.githubusercontent.com/assets/10697310/12701264/e3154894-c825-11e5-990b-6be9322ac623.png)
![2016-01-31_14 17 44](https://cloud.githubusercontent.com/assets/10697310/12701266/e76f0db2-c825-11e5-86ab-2f9263b0bcec.png)

**Comment by Kanol** [comment]
UPD Even if it is the first block of tree, it isn't always looks normaly
![2016-01-31_14 27 58](https://cloud.githubusercontent.com/assets/10697310/12701295/0d088b4c-c827-11e5-929b-7a1632b9c05f.png)

**Comment by octarine-noise** [comment]
Fixed in 2.0.9
