### ISSUE TITLE
Can't get round leaf textures to load

### ISSUE THREAD

**Issue by Qohelethh** [octarine-noise/BetterFoliage#45]
I'm not sure if this is a bug or just user error, but I can't get it to work.
I'm using the 1.7.10 version of this mod (2.0.3) with a 32x texture pack, and I cannot for the life of me get the mod to load the custom round leaf textures I've made. I followed the directions on the Curse Forge page, but it just won't load them.

Here's an example:

My oak leaf texture is located at assets\minecraft\textures\blocks\leaves_oak.png

So I put the round leaf texture at assets/betterfoliage/minecraft/textures/blocks/leaves_oak.png.

I still can't get it to load and I'm beginning to pull my hair out. Any advice?

**Comment by octarine-noise** [comment]
It's a bug. I messed up the order.

Instead of: **assets/betterfoliage/MOD/textures/blocks/TEXTURE.png**
It looks at: **assets/betterfoliage/textures/blocks/MOD/TEXTURE.png**

I'll get it fixed in the next version, in the meantime you can test your textures in the wrong location.

**Comment by Qohelethh** [comment]
Thanks, that worked!

**Comment by octarine-noise** [comment]
Back to normal in 2.0.4
