### ISSUE TITLE
1.8.9-Plant Mega Pack Logs are invisible

### ISSUE THREAD

**Issue by WenXin20** [octarine-noise/BetterFoliage#46]
Plant Mega Pack Beta 2 (http://10paksmods.net/releases.html) Logs appear invisible when round logs are enabled.

**Comment by octarine-noise** [comment]
Tested with Forge 1715, BF 2.0.3, PMP 1.8.9.4. I can't see any problems.

Can you give me exact versions where this problem happens? Maybe it got fixed on PMP's side?

**Comment by WenXin20** [comment]
I tried it with forge 1726 & 1741, PMP 1.8.9.4. I also noticed that when palm logs from Agricultural Revolution (Cooking Plus) Mod was added to the log blocks whitelist, they were also invisible.

**Comment by octarine-noise** [comment]
Fixed in 2.0.4

You must have "Round Logs/Default to vertical" enabled.
