### ISSUE TITLE
OptiFine_1.8.9_HD_U_H5 compatibility

### ISSUE THREAD

**Issue by hexosse** [octarine-noise/BetterFoliage#49]
Hi, 

version 2.0.4 from branch kotlin-1.8.8 is not compatible with OptiFine_1.8.9_HD_U_H5

`java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/client/renderer/chunk/RenderChunk.func_178581_b(FFFLnet/minecraft/client/renderer/chunk/ChunkCompileTaskGenerator;)V @438: aload
  Reason:
    Type top (current frame, locals[24]) is not assignable to reference type
`

**Comment by octarine-noise** [comment]
Release works fine for me.

"branch kotlin-1.8.8" -> are you trying to run it in your dev environment?
