### ISSUE TITLE
BetterFoliage-MC1.9-2.0.4 crashes client on startup with illegal state

### ISSUE THREAD

**Issue by kreezxil** [octarine-noise/BetterFoliage#50]
fml log: http://paste.ee/p/iNJah

crash report: http://paste.ee/p/yCsfu

**Comment by kreezxil** [comment]
BetterFoliage-MC1.9-2.0.5 also crashes client on start up with illegal state when using forge build 1.9-1811

fml latest: http://paste.ee/p/BMhQx

crash report: http://paste.ee/p/9hCez

**Comment by octarine-noise** [comment]
Should be fixed in 2.0.6.
One of the other mods is creating a blockstate with no block. I think that's morally wrong, but I've done worse, so yeah.
I've added a check for it. See if any blocks seem to render glitchy.
