### ISSUE TITLE
Crashes in combination with OptiFine

### ISSUE THREAD

**Issue by schneidermayer** [octarine-noise/BetterFoliage#51]
[crash report](http://pastebin.com/D2pdkXZH)

Author of OptiFine:

> Some of the core mods is manipulating one of the OptiFine classes and fails.
> Probably BetterFoliage is trying to patch RenderChunk.

[go to thread](https://github.com/sp614x/optifine/issues/46)

**Comment by HillustratedMike36** [comment]
I can confirm this, unfortunately...

[Similar Crash Report](http://pastebin.com/qcBabG74)

@sp614x is likely right...

**Comment by dmynerd78** [comment]
I can confirm this as well

[Crash Report](http://pastebin.com/1urH2Yb2)

**Comment by Shores2510** [comment]
Same

[Crash Report](http://pastebin.com/Reca77D5)

**Comment by octarine-noise** [comment]
Fixed in 2.0.5
