### ISSUE TITLE
Some strings not localized

### ISSUE THREAD

**Issue by Ghostlyr** [octarine-noise/BetterFoliage#54]
I was trying to translate some options buttons, but unable to find their localized names and strings in code... Could you please add localizable names it to this strings and their tooltips?

![544665](https://cloud.githubusercontent.com/assets/8511068/14168436/3abfb08c-f744-11e5-973f-cee8752c0f70.png)

**Comment by octarine-noise** [comment]
Those are actually part of Forge, I just use their GUI for my configuration. It probably changed since the last time someone translated it and they're missing some strings.
