### ISSUE TITLE
Ground Glitch

### ISSUE THREAD

**Issue by Sprinksguy28** [octarine-noise/BetterFoliage#55]
Any block that has another block above it will glitch out and be transparent, letting me see through the block and underground. Thanks

**Comment by octarine-noise** [comment]
Give me the versions used, and some screenshots.

**Comment by fatherg** [comment]
I believe I am having the same issue:

http://imgur.com/G2tugc6

Just updated to the latest release of Better Foliage, Forge 1817, optifine 1.9.0_HD_U_B1

as you can see the wood logs and some parts of the terrain are transparent/textureless

**Comment by Sprinksguy28** [comment]
Yes that is the same issue I am having. It is the 2.05 version.

**Comment by Sprinksguy28** [comment]
BetterFoliage - MC1.9-2.05, Optifine_1.9.0_HD_U_B1, BiomesOPlenty -
1.9-4.0.0.1978

**Comment by octarine-noise** [comment]
Do you still have the issue with the latest version (2.0.9)?

**Comment by ghost** [comment]
The problem seems to be related to Optifine.
I solved the problem by switching back from Optifine B2 (preview version) to Optifine B1. (Referring to the latest 2.0.9 version)

**Comment by ghost** [comment]
But to be complete, here are some screenshots with Optifine B2 (preview version)

http://imgur.com/olhqj63 with standard settings for Better Foliage
http://imgur.com/q2VNfx8 the same with Connected Grass Textures turned OFF
http://imgur.com/9qQLkyU the glitch seems to only affect DIRT blocks below water and below trees

As I stated before, switching back to Optifine B1 solved the problem for me. :-)

**Comment by ghost** [comment]
The glitch came back for me after I switched to another resource pack. I tried switching back to default skin, switching Optifine versions, and so on... nothing helped.
The funny thing is, that that glitch was gone after I rebooted my PC and restarted Minecraft. Can't reproduce the glitch right now. Dont' understand :-/

**Comment by octarine-noise** [comment]
I suspect it is OptiFine. Specifically, there was a change introduced in Forge 1817 and OF is still using the old method, while BF is using the new one. I've already reported it on the OF thread, we'll see what happens.

I didn't figure out why the problem is so intermittent, but I had the same problems reproducing it while fixing a related issue for 2.0.9.

**Comment by octarine-noise** [comment]
Latest OptiFine works fine with BF.

**Comment by AfterRebelion** [comment]
@octarine-noise what do you mean by latest? Because i used Optifine U B1 and U B2 pre, and the issue is still there:
![2016-04-26_04 56 07](https://cloud.githubusercontent.com/assets/559819/14805681/6843d900-0b6e-11e6-815e-8aa30be2a446.png)
