### ISSUE TITLE
MC1.9, Forge 12.16.0.1857, OF 1.9.0 B2

### ISSUE THREAD

**Issue by JonnyBrando** [octarine-noise/BetterFoliage#57]
Also using BOP 4.0.0.2003, JEI 3.2.8.182, and JourneyMap 5.1.6b2.

Missing textures for grass (dirt and stone are OK) in newly generated chunks (sides are there, just the top is not displayed), and missing 90% of tree core (redwood especially). Leaves are there, and the particles falling are there as well.

Removed BF 2.0.8 and RedWood core (blocks) are shown again. Grass chunk loading issue still remains.

**Comment by octarine-noise** [comment]
I'll check out support for Redwood. I don't know what could be wrong at first glance.

I think the grass issue, however, has nothing to do with BF. Not if it happens without BF being loaded.

**Comment by JonnyBrando** [comment]
Ya, it's got to be unrelated ... I actually think it's BOP itself.

I updated from build 2000 to 2003. Reverted to 2002, no different.

Removed BOP and it's all fine on a new world. Trying build 2000 again.

**Comment by JonnyBrando** [comment]
Looking at the BOP changelog:

---

Build 1.9-4.0.0.2003:
    forstride: Fixed a few more things for generator settings

Build 1.9-4.0.0.2002:
    forstride: Fixed generator settings

Build 1.8.9-3.0.0.2001:
    Adubbz: Backported mangrove, palm and big tree changes from 1.9

Build 1.9-4.0.0.2000:
    forstride: Added cocoa beans to more trees

---

Perhaps the generator settings messed stuff up ... or ... I need to delete the CFG files moving from build 2000 to 2002+.

**Comment by JonnyBrando** [comment]
Build 2000 - New Config - New World, grass missing in spots, logs do not show, trees spawn 3/4 in ground.

Build 2002 - New Config - New World, grass is working, logs are showing (oak / spruce / acacia), trees spawn normally.

Build 2003 - New Config - New World, grass missing in spots, logs do not show, trees spawn normally.

---

Wierd. Not sure if its forge, or just because BOP is still really beta. The recommended build on the BOP page is 2002, so, I'll stick with it for now :)!

---

False alarm for now, but, I'll be sure to let you know if any trees do not appear correctly with the recommended BOP build!
