### ISSUE TITLE
MC 1.9 / BF 2.0.9 / F1865 / OF 1.9 HD U B2 PRE -- TypeCastException cannot be cast to non-null type Boolean (OF CTM)

### ISSUE THREAD

**Issue by JonnyBrando** [octarine-noise/BetterFoliage#59]
Error message below, full convo is here. Causes crash with Tinkers Construct in latest builds.

https://github.com/SlimeKnights/TinkersConstruct/issues/2036

> [23:41:43] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.TextureStitchEvent$Pre@75892e01:
> mods.octarinecore.kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Boolean
>   at mods.betterfoliage.client.integration.OptifineCTM.getAllCTM(OptifineCTM.kt:51) ~[OptifineCTM.class:?]
>   at mods.betterfoliage.client.texture.LeafRegistry.processTextures(LeafRegistry.kt:69) ~[LeafRegistry.class:?]
>   at mods.betterfoliage.client.texture.LeafRegistry.processTextures(LeafRegistry.kt:42) ~[LeafRegistry.class:?]
>   at mods.octarinecore.client.resource.BlockTextureInspector$onStitch$1.accept(ModelDataInspector.kt:91) ~[BlockTextureInspector$onStitch$1.class:?]
>   at mods.octarinecore.client.resource.BlockTextureInspector$onStitch$1.accept(ModelDataInspector.kt:54) ~[BlockTextureInspector$onStitch$1.class:?]
>   at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_25]
>   at mods.octarinecore.client.resource.BlockTextureInspector.onStitch(ModelDataInspector.kt:87) ~[BlockTextureInspector.class:?]
>   at mods.octarinecore.client.resource.ModelDataInspector.handleTextureReload(ModelDataInspector.kt:51) ~[ModelDataInspector.class:?]
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_13_ModelDataInspector_handleTextureReload_Pre.invoke(.dynamic) ~[?:?]
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
>   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
>   at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:141) [ForgeHooksClient.class:?]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
>   at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
>   at Reflector.callVoid(Reflector.java:309) [Reflector.class:?]
>   at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:179) [bvg.class:?]
>   at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:145) [bvg.class:?]
>   at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:134) [ModelLoader.class:?]
>   at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [bxs.class:?]
>   at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130) [bwl.class:?]
>   at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111) [bwl.class:?]
>   at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:748) [bcf.class:?]
>   at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:323) [FMLClientHandler.class:?]
>   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513) [bcf.class:?]
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346) [bcf.class:?]
>   at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
>   at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by octarine-noise** [comment]
Fixed in 2.0.10
