### ISSUE TITLE
Extra Utils crash

### ISSUE THREAD

**Issue by 63502** [octarine-noise/BetterFoliage#64]
When I have this mod installed, the game crashes when I open a world.
If this is an extra utils error, please tell me so I can post it on that Issues page instead.

Gist:
https://gist.github.com/63502/006bb863d143c608d706f8fbc62297f6

**Comment by Drehverschluss** [comment]
Got exactly the same Error.

**Comment by benten2000** [comment]
Just tired Better myself and I as well get that error pertaining to Extra Utils.

**Comment by octarine-noise** [comment]
Fixed in 2.0.12b.
