### ISSUE TITLE
problem with configuration file

### ISSUE THREAD

**Issue by 0Navis0** [octarine-noise/BetterFoliage#66]
There is a problem with the configuration file. Better Foliage doesn't give a shit about the user choice for the connectedgrass, fallingleaves, risingsoul, roundlogs and shortgrass. In more the mod add two times the same but with one in lowercare and the other in uppercase.

It seems that your mod implements bad the reading and writting function for the configuration file.

**Comment by CrazyManLabs** [comment]
I also faced with this problem!
MC-1.9.4
Forge-12.17.0.1987
BetterFoliage-2.0.12b

**Comment by octarine-noise** [comment]
Fixed in 2.0.13
