### ISSUE TITLE
1.10.2 version?

### ISSUE THREAD

**Issue by miiichael** [octarine-noise/BetterFoliage#77]
Any chance of a version suitable for current Minecraft? Thanks!

**Comment by InvicTech** [comment]
I would really love to see a portation of this mod for 1.10.2 as quite a lot of developers are updating their mods too. I'd like to see at least an alpha version for testing purposes...

**Comment by octarine-noise** [comment]
The 1.10 version came out over a month ago...

**Comment by miiichael** [comment]
Yes, I know there's a 1.10 version, I was asking about a 1.10.2 version, which (according to curseforge at least) doesn't exist...

**Comment by octarine-noise** [comment]
Oh yeah, I only found out it works for 1.10.2 too after uploading. My bad. I've updated the file metadata.

**Comment by miiichael** [comment]
Awesome, thanks! <ticks off one less mod holding back an upgrade from 1.9.4>
