### ISSUE TITLE
Client crash just started happening with new forge and new Better Foliage releases

### ISSUE THREAD

**Issue by Redlotus99** [octarine-noise/BetterFoliage#78]
Just got this.

http://pastebin.com/i5xtQPtb

**Comment by octarine-noise** [comment]
Check with 2.1.1, I believe it might be fixed now.

**Comment by miuirussia** [comment]
Not fixed(

Problem at https://github.com/octarine-noise/BetterFoliage/blob/kotlin-1.10/src/main/kotlin/mods/betterfoliage/client/render/RenderLeaves.kt#L51 leafInfo needs null-check

PS. Please, can you say, how to build BetterFoliage from source?

**Comment by octarine-noise** [comment]
Fixed in 2.1.2
