### ISSUE TITLE
TinkersConstruct Berry Bush Texture

### ISSUE THREAD

**Issue by SirWilli** [octarine-noise/BetterFoliage#8]
Version 1.0.3 on 1.7.10

Image says everything ;)

http://i.imgur.com/Sbxvcby.png

**Comment by Gayanfalor** [comment]
I have the same thing here, i just wanted to disable the mod for all tinkers bushes oreberries bushes etc but i dont know what to put in blacklist.

When i hit f8 and go to leaves blacklist i have this "tconstruct.blocks.OreberryBushEssence" but i dont think its disabling the essence bush.

by the way i'm on  1.0.3 ver too for MC 1.7.10

**Comment by octarine-noise** [comment]
Fixed in 1.0.4
