### ISSUE TITLE
better foliage still doesn't work with TechReborn rubber tree foliage and BiomesOPlenty flowering oak foliage

### ISSUE THREAD

**Issue by 0Navis0** [octarine-noise/BetterFoliage#80]
The dense foliage effect still doesn't work with these foliages. :(

**Comment by octarine-noise** [comment]
BoP flowering oak leaves should work as of 2.1.2.

TechReborn rubber is work in progress.

**Comment by 0Navis0** [comment]
It doesn't work with AbyssalCraft darkland and dreadland leaves, EvilCraft undead leaves, and IntegratedDynamics menril leaves.

**Comment by octarine-noise** [comment]
Fixed in 2.1.5.

Don't forget to reset your block types config to default.
