### ISSUE TITLE
Extra details on certain leaves not appearing on 1.10.2

### ISSUE THREAD

**Issue by timewarp1** [octarine-noise/BetterFoliage#83]
http://puu.sh/qVPWe/2a0a233acd.jpg

Mods installed:
MCP 9.19
FML 8.0.99.99
Forge 12.18.1.2076
Better Foliage 2.1.0
http://puu.sh/qVPZs/c9a6476125.jpg

Also tried with the recommended version of Forge, 12.18.1.2011, and the issue remained present.

Interestingly, the leaves from Tinker's Construct, Biomes O' Plenty, and Abyssalcraft all seem to work as expected. It's just vanilla, Forestry, and Tech Reborn leaves that aren't rendering the details.
http://puu.sh/qVQmB/7f9fe3f520.jpg

Here is the config file I'm using, I haven't changed anything in it:
http://pastebin.com/E8AMFPhX

**Comment by ghost** [comment]
short grass not appearing too on 1.10.2(

**Comment by Towdium** [comment]
@MrEvilCookie  +1

**Comment by octarine-noise** [comment]
Fixed in 2.1.1
