### ISSUE TITLE
Config Doesn't Save

### ISSUE THREAD

**Issue by WenXin20** [octarine-noise/BetterFoliage#88]
If I go into the config file, I find two sections on round logs, but neither seem to work to change the options set to false to true. When I start the game, it seems to reset to false again.
Forge 2092

**Comment by WenXin20** [comment]
It looks like all the configs reset after each game launch.

**Comment by WenXin20** [comment]
By the way, this was using version 2.1.1

**Comment by ThaUnknown** [comment]
happens the same to me :(

**Comment by octarine-noise** [comment]
Weird... 2.1.x versions shouldn't have this bug anymore.

Please try using 2.1.2 and deleting your BetterFoliage.cfg, and see if it still happens.
