### ISSUE TITLE
Crash with MineFactoryReloaded

### ISSUE THREAD

**Issue by Adaptivity** [octarine-noise/BetterFoliage#9]
http://pastebin.com/hXLRqU1G it happens randomly in the world. This caused by Better Foliage as skyboy (MFR dev) said. Tested on Forge 1286, latest MFR and Better Foliage.
Another crash but know something with Natura: http://pastebin.com/YsL5u1ap

**Comment by octarine-noise** [comment]
Seems to be some strange case I've not considered.
I've added some code in version 1.0.4 to stop crashing and log the error. Look for messages like "ArrayIndexOutOfBounds when rendering block" in your log and/or graphical glitches to see if the problem persists.
Closing for now.

**Comment by Adaptivity** [comment]
Thanks for looking. It might be not BetterFoliage and not MFR. I dunno why they both mentioned in log. I'll continue investigation.
