### ISSUE TITLE
BiomesOPlenty Mega-Flower Tree Leaves

### ISSUE THREAD

**Issue by ElvenChaos** [octarine-noise/BetterFoliage#92]
Is there a way to block the tree leaf effects on -just- the BOP flower-trees? The two blocks in question are the Giant Red Flower Petal and the Giant Yellow Flower Petal (biomesoplenty:leaves_6:8 and biomesoplenty:leaves_6:9). I don't want to block all of BoP's trees through its class.

**Comment by Graagh** [comment]
Possibly, providing a blank texture for the better leaves of those blocks might work.
