### ISSUE TITLE
Where are the grass sides option?

### ISSUE THREAD

**Issue by ghost** [octarine-noise/BetterFoliage#95]
I can't find this option and it used to be my favorite. WHERE?
Also I want this (REQUEST): Make sure some options that require minecraft restart are quick-changeable and don't require a restart to take effect. This worked earlier but you decided to make sure it works after a restart. Please fix that.

**Comment by octarine-noise** [comment]
The "hanging grass" feature was temporarily removed, it will probably make a comeback when I have some time to tinker with it.

The config problems are worked out in more recent versions.
