### ISSUE TITLE
Extra Leaves Only Render On Decayable Forestry Leaves

### ISSUE THREAD

**Issue by ChloeDawn** [octarine-noise/BetterFoliage#98]
Non-decaying Forestry leaves don't render the extra leaves model.

Example (Teak leaves from Forestry):

![2016-11-07_22 44 41](https://cloud.githubusercontent.com/assets/9869940/20079253/c8f5b748-a53b-11e6-9589-20097c176136.png)

EDIT: This is due to the non-decaying leaves in Forestry extending `Block` instead of `BlockLeaves` for better performance. Is there any way around this?

EDIT 2: This issue also occurs with Biomes O' Plenty flowering oak leaves.

![2016-11-07_23 13 24](https://cloud.githubusercontent.com/assets/9869940/20080092/cb3b2df4-a53f-11e6-936d-477f5a684413.png)

Mod version: **[2.1.1](https://minecraft.curseforge.com/projects/better-foliage/files/2330620)**
Minecraft version: **[1.10.2](https://mojang.com/2016/06/minecraft-1101/)**
Forge version: **[12.18.2.2122](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.2.2122/forge-1.10.2-12.18.2.2122-changelog.txt)**

**Comment by octarine-noise** [comment]
Fixed in 2.1.2
