### ISSUE TITLE
Better check for Leaf blocks. Fixes compatibility with Aether Leaves.

### ISSUE THREAD

**Issue by kingbdogz** [octarine-noise/BetterFoliage#99]
Hi,

I'm a dev from the Aether team, and I'd like to propose another check for leaf blocks. Right now I assume you check if the Block class inherits BlockLeaves.

I propose you also have a second check which checks against the "isLeaves()" method in Block.

For certain reasons I won't delve into, our leaves cannot extend BlockLeaves, so having this check as well would improve compatibility between our mods (and likely other mods as well).

Thank you.

**Comment by octarine-noise** [comment]
Not deriving leaf blocks from **BlockLeaves** is actually a lot more common than you'd realize ;)

I use a blacklist/whitelist filtering for that reason, and now I've added Aether leaves to the defaults.

Fixed in 2.1.2
